// Game content for "Isekai Adventure" — data only, no logic.
// Balanced for the full Base Lv 1 -> 80 journey.
export const CONTENT = {
  monsters: [
    { id: "slime", name: "Gel Slime", flavor: "A wobbling blob. Your first foe in this new world.",
      level: 2, hp: 75, atk: 10, def: 4, exp: 7, spriteColor: "#4fc3f7", sizeTiles: 1,
      drops: [{ itemId: "slime_gel", chance: 0.7 }, { itemId: "minor_potion", chance: 0.1 }], behavior: "passive" },
    { id: "goblin", name: "Scrap Goblin", flavor: "A scrawny raider that jabs with a rusty knife.",
      level: 5, hp: 116, atk: 16, def: 6, exp: 37, spriteColor: "#8bc34a", sizeTiles: 1,
      drops: [{ itemId: "goblin_ear", chance: 0.6 }, { itemId: "iron_helm", chance: 0.05 }, { itemId: "worn_dagger", chance: 0.15 }, { itemId: "minor_potion", chance: 0.15 }], behavior: "aggressive" },
    { id: "wolf", name: "Dire Wolf", flavor: "Lean, fast, and always hunting in the woods.",
      level: 9, hp: 170, atk: 23, def: 9, exp: 111, spriteColor: "#9e9e9e", sizeTiles: 1,
      drops: [{ itemId: "wolf_pelt", chance: 0.6 }, { itemId: "iron_boots", chance: 0.06 }, { itemId: "wolf_fang", chance: 0.35 }], behavior: "aggressive" },
    { id: "thornback_boar", name: "Thornback Boar", flavor: "Bramble roots armor its hide and splinter anyone who stands their ground.",
      level: 12, hp: 218, atk: 31, def: 12, exp: 190, spriteColor: "#8f6b45", sizeTiles: 1,
      drops: [{ itemId: "wolf_pelt", chance: 0.45 }, { itemId: "wolf_fang", chance: 0.25 }, { itemId: "mid_potion", chance: 0.12 }], behavior: "aggressive" },
    { id: "mossback_beetle", name: "Mossback Beetle", flavor: "A patient shell-creeper that carries half the forest on its back.",
      level: 6, hp: 132, atk: 18, def: 7, exp: 48, spriteColor: "#5f9f63", sizeTiles: 1,
      drops: [{ itemId: "slime_gel", chance: 0.35 }, { itemId: "wolf_pelt", chance: 0.2 }], behavior: "passive" },
    { id: "shade", name: "Woodland Shade", flavor: "A restless spirit bound to the ruins' edge.",
      level: 21, hp: 332, atk: 46, def: 19, exp: 531, spriteColor: "#7e57c2", sizeTiles: 1,
      drops: [{ itemId: "shade_dust", chance: 0.5 }, { itemId: "warding_cloak", chance: 0.06 }, { itemId: "iron_gauntlets", chance: 0.05 }, { itemId: "mid_potion", chance: 0.2 }, { itemId: "mana_potion", chance: 0.2 }], behavior: "aggressive", attackRange: 3.5, attackCooldownMult: 1.25, projectileColor: "#c99aef" },
    { id: "mire_leech", name: "Mire Leech", flavor: "A pale feeder swollen on memories leaking from the drowned dead.",
      level: 18, hp: 295, atk: 40, def: 16, exp: 395, spriteColor: "#6f8f72", sizeTiles: 1,
      drops: [{ itemId: "shade_dust", chance: 0.35 }, { itemId: "mid_potion", chance: 0.18 }, { itemId: "mana_potion", chance: 0.12 }], behavior: "aggressive" },
    { id: "drowned_acolyte", name: "Drowned Acolyte", flavor: "An abbey novice still chanting through lungs full of black water.",
      level: 25, hp: 390, atk: 58, def: 21, exp: 720, spriteColor: "#5f9fa5", sizeTiles: 1,
      drops: [{ itemId: "shade_dust", chance: 0.55 }, { itemId: "warding_cloak", chance: 0.04 }, { itemId: "mana_potion", chance: 0.24 }], behavior: "aggressive", attackRange: 4, attackCooldownMult: 1.3, projectileColor: "#7ed6d9" },
    { id: "ruin_crawler", name: "Ruin Crawler", flavor: "Stone plates click beneath the drowned halls as it searches for warmth.",
      level: 22, hp: 348, atk: 50, def: 20, exp: 610, spriteColor: "#8b7b68", sizeTiles: 1,
      drops: [{ itemId: "golem_core", chance: 0.08 }, { itemId: "shade_dust", chance: 0.3 }], behavior: "aggressive" },
    { id: "elderwood_treant", name: "Elderwood Treant", flavor: "The forest's oldest warden. It does not forgive the axe.",
      level: 14, hp: 853, atk: 41, def: 16, exp: 1004, spriteColor: "#4e8a3f", sizeTiles: 2,
      drops: [{ itemId: "blessed_ore", chance: 0.5 }, { itemId: "leather_vest", chance: 0.35 }, { itemId: "mid_potion", chance: 1.0 }], behavior: "aggressive" },
    { id: "frost_revenant", name: "Frost Revenant", flavor: "A king who froze on his throne and never noticed he died.",
      level: 44, hp: 1650, atk: 112, def: 44, exp: 8340, spriteColor: "#bfe6ff", sizeTiles: 2,
      drops: [{ itemId: "ice_core", chance: 1.0 }, { itemId: "frost_brand", chance: 0.2 }, { itemId: "blessed_ore", chance: 0.6 }, { itemId: "greater_potion", chance: 0.8 }], behavior: "aggressive" },
    { id: "gilded_ravager", name: "Gilded Ravager", flavor: "A nomad tyrant crowned in stolen gold. It answers to no zone and fears no guardian.",
      level: 45, hp: 1700, atk: 116, def: 45, exp: 9000, spriteColor: "#f2ca59", sizeTiles: 2, rare: true,
      drops: [{ itemId: "blessed_ore", chance: 1.0 }, { itemId: "elixir", chance: 0.65 }, { itemId: "gold_ring", chance: 0.35 }, { itemId: "star_pendant", chance: 0.2 }, { itemId: "frost_brand", chance: 0.08 }], behavior: "aggressive" },
    { id: "ruin_golem", name: "Ruin Golem", flavor: "An ancient guardian of stone. The trial that seals your arrival.",
      level: 28, hp: 1150, atk: 74, def: 29, exp: 3616, spriteColor: "#795548", sizeTiles: 2,
      drops: [{ itemId: "golem_core", chance: 1.0 }, { itemId: "hero_blade", chance: 0.5 }, { itemId: "vitality_amulet", chance: 0.4 }, { itemId: "mid_potion", chance: 1.0 }], behavior: "aggressive" },

    // ===== Expansion monsters (Frostpeak & Dragon Caldera) =====
    { id: "frost_wolf", name: "Frost Wolf", flavor: "A wolf of living ice, hunting the white silence.",
      level: 32, hp: 480, atk: 74, def: 28, exp: 1157, spriteColor: "#9fe6ff", sizeTiles: 1,
      drops: [{ itemId: "frost_shard", chance: 0.6 }, { itemId: "knight_plate", chance: 0.04 }, { itemId: "wolf_pelt", chance: 0.4 }, { itemId: "greater_potion", chance: 0.15 }, { itemId: "blessed_ore", chance: 0.08 }], behavior: "aggressive" },
    { id: "ice_wraith", name: "Ice Wraith", flavor: "A frozen soul that drifts the peaks, chilling to the bone.",
      level: 37, hp: 548, atk: 86, def: 32, exp: 1513, spriteColor: "#bfe6ff", sizeTiles: 1,
      drops: [{ itemId: "frost_shard", chance: 0.5 }, { itemId: "ice_core", chance: 0.3 }, { itemId: "silver_amulet", chance: 0.04 }, { itemId: "aurora_cloak", chance: 0.05 }, { itemId: "mana_potion", chance: 0.25 }], behavior: "aggressive", attackRange: 4, attackCooldownMult: 1.3, projectileColor: "#bfe6ff" },
    { id: "rime_harpy", name: "Rime Harpy", flavor: "It rides the knife-wind, hurling frozen feathers at anything warm.",
      level: 41, hp: 610, atk: 96, def: 36, exp: 1775, spriteColor: "#80c8d8", sizeTiles: 1,
      drops: [{ itemId: "frost_shard", chance: 0.55 }, { itemId: "ice_core", chance: 0.2 }, { itemId: "aurora_cloak", chance: 0.04 }, { itemId: "mana_potion", chance: 0.2 }], behavior: "aggressive", attackRange: 3.5, attackCooldownMult: 1.15, projectileColor: "#d7f4ff" },
    { id: "tundra_lurker", name: "Tundra Lurker", flavor: "It vanishes beneath powder snow, leaving only a trail of frost shards.",
      level: 39, hp: 575, atk: 90, def: 34, exp: 1600, spriteColor: "#77b7c9", sizeTiles: 1,
      drops: [{ itemId: "frost_shard", chance: 0.4 }, { itemId: "ice_core", chance: 0.12 }], behavior: "aggressive" },
    { id: "sand_stalker", name: "Sand Stalker", flavor: "It waits beneath the dunes; you only hear it once.",
      level: 52, hp: 750, atk: 140, def: 44, exp: 2840, spriteColor: "#d9c18f", sizeTiles: 1,
      drops: [{ itemId: "sand_fang", chance: 0.6 }, { itemId: "gold_ring", chance: 0.03 }, { itemId: "drakescale_boots", chance: 0.05 }, { itemId: "greater_potion", chance: 0.2 }, { itemId: "blessed_ore", chance: 0.08 }], behavior: "aggressive" },
    { id: "ember_imp", name: "Ember Imp", flavor: "A gleeful little devil made of coals and spite.",
      level: 47, hp: 682, atk: 128, def: 40, exp: 2356, spriteColor: "#e0714b", sizeTiles: 1,
      drops: [{ itemId: "ember_ash", chance: 0.6 }, { itemId: "star_pendant", chance: 0.02 }, { itemId: "mythril_gauntlets", chance: 0.05 }, { itemId: "mana_potion", chance: 0.25 }, { itemId: "mythril_sword", chance: 0.05 }], behavior: "aggressive", attackRange: 3.5, attackCooldownMult: 1.15, projectileColor: "#ff8b3d" },
    { id: "magma_beetle", name: "Magma Beetle", flavor: "Its basalt shell seals a furnace-hot core that cracks open when angered.",
      level: 56, hp: 830, atk: 151, def: 48, exp: 3150, spriteColor: "#c45d32", sizeTiles: 1,
      drops: [{ itemId: "ember_ash", chance: 0.55 }, { itemId: "blessed_ore", chance: 0.1 }, { itemId: "drakescale_boots", chance: 0.04 }, { itemId: "greater_potion", chance: 0.18 }], behavior: "aggressive" },
    { id: "ashwing", name: "Ashwing", flavor: "A soot-feathered flier that nests in the caldera's warmest vents.",
      level: 54, hp: 790, atk: 145, def: 45, exp: 3000, spriteColor: "#d77b4c", sizeTiles: 1,
      drops: [{ itemId: "ember_ash", chance: 0.4 }, { itemId: "drakescale_boots", chance: 0.03 }], behavior: "aggressive", attackRange: 3.5, projectileColor: "#ff9b5c" },
    { id: "flame_dragon", name: "Flame Dragon", flavor: "The tyrant of the caldera. Its roar is the last thing many hear.",
      level: 60, hp: 2250, atk: 150, def: 60, exp: 14804, spriteColor: "#e2551f", sizeTiles: 2,
      drops: [{ itemId: "dragon_heart", chance: 1.0 }, { itemId: "dawn_edge", chance: 0.6 }, { itemId: "dragon_helm", chance: 0.5 }, { itemId: "elixir", chance: 1.0 }], behavior: "aggressive" },

    // ===== Astral Rift (endgame biome, Lv 61-80) =====
    { id: "void_wisp", name: "Void Wisp", flavor: "A mote of unmade reality, drifting where the stars leak through.",
      level: 63, hp: 898, atk: 168, def: 52, exp: 4051, spriteColor: "#9d80d6", sizeTiles: 1,
      drops: [{ itemId: "void_shard", chance: 0.6 }, { itemId: "comet_ring", chance: 0.03 }, { itemId: "astral_greaves", chance: 0.04 }, { itemId: "mana_potion", chance: 0.25 }, { itemId: "celestial_draught", chance: 0.08 }], behavior: "aggressive", attackRange: 4, attackCooldownMult: 1.3, projectileColor: "#b6a0e6" },
    { id: "star_reaver", name: "Star Reaver", flavor: "A warrior long dead, still swinging a blade of cold starlight.",
      level: 68, hp: 966, atk: 178, def: 56, exp: 4665, spriteColor: "#b6a0e6", sizeTiles: 1,
      drops: [{ itemId: "star_iron", chance: 0.5 }, { itemId: "void_shard", chance: 0.4 }, { itemId: "void_edge", chance: 0.05 }, { itemId: "voidweave_cloak", chance: 0.04 }, { itemId: "blessed_ore", chance: 0.08 }], behavior: "aggressive" },
    { id: "astral_knight", name: "Astral Knight", flavor: "A sentinel of the rift, armored in condensed moonlight.",
      level: 73, hp: 1034, atk: 192, def: 60, exp: 5320, spriteColor: "#dfe6ff", sizeTiles: 1,
      drops: [{ itemId: "star_iron", chance: 0.5 }, { itemId: "astral_plate", chance: 0.06 }, { itemId: "void_helm", chance: 0.08 }, { itemId: "titan_grips", chance: 0.05 }, { itemId: "greater_potion", chance: 0.2 }], behavior: "aggressive" },
    { id: "rift_manta", name: "Rift Manta", flavor: "A silent sky-ray that swims between broken constellations and hunts by starlight.",
      level: 76, hp: 1110, atk: 199, def: 64, exp: 5520, spriteColor: "#8f7bd6", sizeTiles: 1,
      drops: [{ itemId: "void_shard", chance: 0.55 }, { itemId: "star_iron", chance: 0.35 }, { itemId: "voidweave_cloak", chance: 0.04 }, { itemId: "celestial_draught", chance: 0.08 }], behavior: "aggressive", attackRange: 4.5, attackCooldownMult: 1.35, projectileColor: "#d2b7ff" },
    { id: "constellation_mite", name: "Constellation Mite", flavor: "A tiny star-eater that skitters across broken paths between worlds.",
      level: 70, hp: 1000, atk: 184, def: 58, exp: 4900, spriteColor: "#a99be5", sizeTiles: 1,
      drops: [{ itemId: "star_iron", chance: 0.35 }, { itemId: "void_shard", chance: 0.3 }], behavior: "aggressive" },
    { id: "nullking", name: "The Nullking", flavor: "The crowned end of all things. It does not roar — it simply unmakes.",
      level: 80, hp: 3500, atk: 198, def: 79, exp: 25208, spriteColor: "#7a4fd0", sizeTiles: 2,
      drops: [{ itemId: "null_core", chance: 1.0 }, { itemId: "astral_glaive", chance: 0.7 }, { itemId: "astral_signet", chance: 0.6 }, { itemId: "elixir", chance: 1.0 }], behavior: "aggressive" }
  ],

  items: [
    // Weapons
    { id: "worn_dagger", name: "Worn Dagger", type: "weapon", desc: "A chipped blade, better than bare fists.", atk: 4, value: 30, classReq: null, gearLevel: 1 },
    { id: "iron_sword", name: "Iron Sword", type: "weapon", desc: "Standard adventurer's steel.", atk: 10, value: 150, classReq: ["reborn_blade", "lightbringer"], gearLevel: 10 },
    { id: "hero_blade", name: "Otherworld Blade", type: "weapon", desc: "A sword that hums to those not born of this world.", atk: 22, value: 800, classReq: ["reborn_blade", "lightbringer"], gearLevel: 25 },
    // Early weapon progression (T4 spec)
    { id: "training_greatsword", name: "Training Greatsword", type: "weapon", desc: "A heavy practice blade.", atk: 8, value: 80, classReq: ["reborn_blade", "lightbringer"], gearLevel: 5 },
    { id: "scrap_scythe", name: "Scrap Scythe", type: "weapon", desc: "A jagged farming tool adapted for war.", atk: 8, value: 80, classReq: ["drifter"], gearLevel: 5 },
    { id: "hunter_bow", name: "Hunter Bow", type: "weapon", desc: "A simple wooden bow.", atk: 8, value: 80, classReq: ["far_shot"], gearLevel: 5 },
    { id: "apprentice_staff", name: "Apprentice Staff", type: "weapon", desc: "A simple focus for beginners.", atk: 8, value: 80, classReq: ["codeweaver", "stormcaller"], gearLevel: 5 },
    { id: "leather_knuckles", name: "Leather Knuckles", type: "weapon", desc: "Reinforced wraps to protect the hands.", atk: 8, value: 80, classReq: ["iron_fist"], gearLevel: 5 },
    { id: "novice_mace", name: "Novice Mace", type: "weapon", desc: "A simple wooden club.", atk: 8, value: 80, classReq: ["lightbringer"], gearLevel: 5 },
    // Mid/late weapon progression (T4 spec)
    { id: "mythril_greatsword", name: "Mythril Greatsword", type: "weapon", desc: "Light but shattering heavy greatsword.", atk: 32, value: 1800, classReq: ["reborn_blade", "lightbringer"], gearLevel: 35 },
    { id: "crimson_scythe", name: "Crimson Scythe", type: "weapon", desc: "A curved blade smelling of old battles.", atk: 30, value: 1600, classReq: ["drifter"], gearLevel: 35 },
    { id: "frost_bow", name: "Frost Bow", type: "weapon", desc: "Each loose arrow trails cold wind.", atk: 30, value: 1600, classReq: ["far_shot"], gearLevel: 35 },
    { id: "rune_staff", name: "Rune Staff", type: "weapon", desc: "Carved with basic focus runes.", atk: 30, value: 1600, classReq: ["codeweaver", "stormcaller"], gearLevel: 35 },
    { id: "dragon_claws", name: "Dragon Claws", type: "weapon", desc: "Spiked gauntlets forged in caldera ash.", atk: 30, value: 1600, classReq: ["iron_fist"], gearLevel: 35 },
    { id: "dawn_mace", name: "Dawn Mace", type: "weapon", desc: "Mace blessed under morning sunlight.", atk: 30, value: 1600, classReq: ["lightbringer"], gearLevel: 35 },
    // Late weapon progression (T4 spec)
    { id: "astral_greatsword", name: "Astral Greatsword", type: "weapon", desc: "Greatsword forged of stellar iron.", atk: 58, value: 7500, classReq: ["reborn_blade", "lightbringer"], gearLevel: 65 },
    { id: "void_scythe", name: "Void Scythe", type: "weapon", desc: "Reaps the empty space between foes.", atk: 56, value: 7000, classReq: ["drifter"], gearLevel: 65 },
    { id: "starhawk_bow", name: "Starhawk Bow", type: "weapon", desc: "Whispers of the night wind follow the arrow.", atk: 56, value: 7000, classReq: ["far_shot"], gearLevel: 65 },
    { id: "astral_staff", name: "Astral Staff", type: "weapon", desc: "A staff capped with a fallen star.", atk: 56, value: 7000, classReq: ["codeweaver", "stormcaller"], gearLevel: 65 },
    { id: "star_knuckles", name: "Star Knuckles", type: "weapon", desc: "Fists that strike like falling meteorites.", atk: 56, value: 7000, classReq: ["iron_fist"], gearLevel: 65 },
    { id: "seraph_mace", name: "Seraph Mace", type: "weapon", desc: "Mace containing divine protection.", atk: 56, value: 7000, classReq: ["lightbringer"], gearLevel: 65 },
    // Armor
    { id: "cloth_tunic", name: "Traveler's Tunic", type: "armor", desc: "Simple cloth you woke up wearing.", def: 2, value: 20, classReq: null },
    { id: "leather_vest", name: "Leather Vest", type: "armor", desc: "Boiled leather that turns a claw or two.", def: 6, value: 120, classReq: ["drifter", "far_shot", "iron_fist"] },
    { id: "guardian_plate", name: "Guardian Plate", type: "armor", desc: "Forged from a golem's core. Heavy but true.", def: 14, value: 700, classReq: ["reborn_blade", "lightbringer"] },
    // Potions
    { id: "minor_potion", name: "Minor Potion", type: "potion", desc: "Restores a little health.", hpRestore: 30, value: 15, classReq: null },
    { id: "mid_potion", name: "Health Potion", type: "potion", desc: "Restores a good amount of health.", hpRestore: 90, value: 45, classReq: null },
    { id: "mana_potion", name: "Mana Potion", type: "potion", desc: "Restores magic power.", mpRestore: 50, value: 40, classReq: null },
    // Materials (monster drops)
    { id: "slime_gel", name: "Slime Gel", type: "material", desc: "Sticky residue. Alchemists pay for it.", value: 5, classReq: null },
    { id: "goblin_ear", name: "Goblin Ear", type: "material", desc: "Proof of a felled goblin.", value: 8, classReq: null },
    { id: "wolf_pelt", name: "Beast Pelt", type: "material", desc: "Warm grey fur.", value: 18, classReq: null },
    { id: "wolf_fang", name: "Beast Fang", type: "material", desc: "A sharp trophy.", value: 25, classReq: null },
    { id: "shade_dust", name: "Shade Dust", type: "material", desc: "Faintly glowing spectral ash.", value: 40, classReq: null },
    { id: "golem_core", name: "Golem Core", type: "material", desc: "The still-warm heart of the Ruin Golem.", value: 250, classReq: null },
    // Quest items
    { id: "guide_letter", name: "Guide's Letter", type: "quest", desc: "A sealed note from the one who summoned you.", value: 0, classReq: null },
    { id: "ancient_seal", name: "Ancient Seal", type: "quest", desc: "Unlocks the ruins beyond the woods.", value: 0, classReq: null },

    // ===== Expansion gear & drops =====
    { id: "mythril_sword", name: "Mythril Sword", type: "weapon", desc: "Light as a feather, sharp as regret.", atk: 30, value: 1500, classReq: ["reborn_blade", "lightbringer"], rankReq: "D", gearLevel: 45 },
    { id: "frost_brand", name: "Frost Brand", type: "weapon", desc: "A blade sheathed in eternal rime.", atk: 37, value: 2600, classReq: ["reborn_blade", "lightbringer"], rankReq: "C", gearLevel: 55 },
    { id: "dawn_edge", name: "Dawn Edge", type: "weapon", desc: "Forged from a dragon's heart; it glows at sunrise.", atk: 47, value: 5200, classReq: ["reborn_blade", "lightbringer"], gearLevel: 65 },
    { id: "mythril_plate", name: "Mythril Plate", type: "armor", desc: "Impossibly strong, impossibly light.", def: 22, value: 2000, classReq: ["reborn_blade", "lightbringer"], rankReq: "D" },
    { id: "seraph_ward", name: "Seraph Ward", type: "armor", desc: "Armor blessed against dragonfire.", def: 29, value: 4200, classReq: ["reborn_blade", "lightbringer"], rankReq: "C" },
    { id: "greater_potion", name: "Greater Potion", type: "potion", desc: "Restores a large amount of health.", hpRestore: 220, value: 120, classReq: null },
    { id: "elixir", name: "Elixir", type: "potion", desc: "Restores health and magic in a single draught.", hpRestore: 500, mpRestore: 200, value: 400, classReq: null },
    { id: "frost_shard", name: "Frost Shard", type: "material", desc: "A sliver of everlasting ice.", value: 45, classReq: null },
    { id: "ice_core", name: "Ice Core", type: "material", desc: "The frozen heart of a wraith.", value: 90, classReq: null },
    { id: "sand_fang", name: "Sand Fang", type: "material", desc: "A venom-tipped fang.", value: 70, classReq: null },
    { id: "ember_ash", name: "Ember Ash", type: "material", desc: "Ash that never cools.", value: 85, classReq: null },
    { id: "dragon_heart", name: "Dragon Heart", type: "material", desc: "Still smouldering. Worth a fortune — or a legendary forge.", value: 800, classReq: null },

    // ===== Equipment slots: head / hands / feet / cloak / accessory =====
    { id: "iron_helm", name: "Iron Helm", type: "armor", slot: "head", desc: "Dented but dependable.", def: 8, value: 400, classReq: ["reborn_blade", "lightbringer"] },
    { id: "dragon_helm", name: "Dragon Helm", type: "armor", slot: "head", desc: "Crowned with a drake's horn.", def: 16, value: 3000, classReq: ["reborn_blade", "lightbringer"] },
    { id: "iron_gauntlets", name: "Iron Gauntlets", type: "armor", slot: "hands", desc: "A solid grip and a solid punch.", def: 6, value: 350, classReq: ["reborn_blade", "lightbringer"] },
    { id: "iron_boots", name: "Iron Boots", type: "armor", slot: "feet", desc: "Heavy, but sure-footed.", def: 6, value: 350, classReq: ["reborn_blade", "lightbringer"] },
    { id: "warding_cloak", name: "Warding Cloak", type: "armor", slot: "cloak", desc: "Woven with faint protective runes.", def: 5, value: 500, classReq: null },
    { id: "power_ring", name: "Power Ring", type: "accessory", slot: "accessory", desc: "It hums with borrowed strength.", atk: 6, value: 800, classReq: null },
    { id: "vitality_amulet", name: "Vitality Amulet", type: "accessory", slot: "accessory", desc: "Steadies the heart in battle.", def: 6, value: 800, classReq: null },

    // ===== Astral Rift gear & drops =====
    { id: "void_edge", name: "Void Edge", type: "weapon", desc: "A blade that cuts the space between things.", atk: 56, value: 7000, classReq: ["reborn_blade", "lightbringer"], rankReq: "B", gearLevel: 70 },
    { id: "astral_glaive", name: "Astral Glaive", type: "weapon", desc: "Forged from a fallen star; it weighs nothing and ends everything.", atk: 66, value: 12000, classReq: ["reborn_blade", "lightbringer"], gearLevel: 80 },
    { id: "astral_plate", name: "Astral Plate", type: "armor", desc: "Woven starlight, hard as fate.", def: 34, value: 9000, classReq: ["reborn_blade", "lightbringer"], rankReq: "B" },
    { id: "void_helm", name: "Void Helm", type: "armor", slot: "head", desc: "A crown of the rift's own dark.", def: 20, value: 6000, classReq: null },
    { id: "astral_signet", name: "Astral Signet", type: "accessory", slot: "accessory", desc: "A ring that remembers the shape of stars.", atk: 12, value: 5000, classReq: null },
    { id: "celestial_draught", name: "Celestial Draught", type: "potion", desc: "Starlight in a vial — restores body and mind fully.", hpRestore: 900, mpRestore: 400, value: 700, classReq: null },
    { id: "void_shard", name: "Void Shard", type: "material", desc: "A splinter of nothing. It hurts to look at.", value: 120, classReq: null },
    { id: "star_iron", name: "Star Iron", type: "material", desc: "Metal that fell from the sky, still humming.", value: 160, classReq: null },
    { id: "null_core", name: "Null Core", type: "material", desc: "The heart of the Nullking. The end of a legend, in your hand.", value: 1500, classReq: null },

    // ===== Buff foods, teleport, refinement material =====
    { id: "sharpening_stone", name: "Sharpening Stone", type: "potion", desc: "Hones your edge — +15% ATK for 60s.", buff: { stat: "atk", mult: 1.15, durationMs: 60000 }, value: 80, classReq: null },
    { id: "iron_tonic", name: "Iron Tonic", type: "potion", desc: "Skin like steel — +15% DEF for 60s.", buff: { stat: "def", mult: 1.15, durationMs: 60000 }, value: 80, classReq: null },
    { id: "teleport_scroll", name: "Teleport Scroll", type: "potion", desc: "Tears a rift straight back to town.", teleport: "town_awakening", value: 60, classReq: null },
    { id: "soul_ledger", name: "Soul Ledger", type: "reset", desc: "Refunds every allocated stat point. Levels, gear, and permanent rebirth bonuses remain.", reset: "stats", value: 1200, classReq: null },
    { id: "memory_prism", name: "Memory Prism", type: "reset", desc: "Refunds spent active and passive skill points. Your free starter skill remains at Lv1.", reset: "skills", value: 1600, classReq: null },
    { id: "blessed_ore", name: "Blessed Ore", type: "material", desc: "Star-touched ore the smiths crave for refinement.", value: 150, classReq: null },

    // ===== Rank-tier accessories =====
    { id: "bronze_ring", name: "Bronze Ring", type: "accessory", slot: "accessory", desc: "A trader's trinket, unremarkable but sturdy.", atk: 5, value: 600, classReq: null, rankReq: "E-" },
    { id: "silver_amulet", name: "Silver Amulet", type: "accessory", slot: "accessory", desc: "Cool to the touch, it steadies a racing heart.", def: 9, value: 1200, classReq: null, rankReq: "D-" },
    { id: "gold_ring", name: "Gold Ring", type: "accessory", slot: "accessory", desc: "Gaudy, heavy, and undeniably potent.", atk: 12, value: 2400, classReq: null, rankReq: "C-" },
    { id: "star_pendant", name: "Star Pendant", type: "accessory", slot: "accessory", desc: "A shard of the night sky, warm against the skin.", def: 15, value: 4500, classReq: null, rankReq: "B-" },
    { id: "comet_ring", name: "Comet Ring", type: "accessory", slot: "accessory", desc: "Trails a faint streak of light with every swing.", atk: 18, value: 8000, classReq: null, rankReq: "A-" },
    { id: "transcendent_sigil", name: "Transcendent Sigil", type: "accessory", slot: "accessory", desc: "A mark worn by legends who outgrew mortal limits.", atk: 14, def: 14, value: 15000, classReq: null, rankReq: "S" },

    // ===== Gap-filler gear =====
    { id: "steel_sword", name: "Steel Sword", type: "weapon", desc: "Well-balanced steel, a cut above the basics.", atk: 14, value: 400, classReq: ["reborn_blade", "lightbringer"], rankReq: "E-", gearLevel: 15 },
    { id: "knight_plate", name: "Knight's Plate", type: "armor", desc: "Ceremonial armor still fit for a real fight.", def: 18, value: 1100, classReq: ["reborn_blade", "lightbringer"], rankReq: "D-" },

    // ===== Mid/late hands-feet-cloak (these slots had no upgrade past the iron set) =====
    { id: "mythril_gauntlets", name: "Mythril Gauntlets", type: "armor", slot: "hands", desc: "Featherlight mesh that punches like plate.", def: 12, value: 900, classReq: null },
    { id: "drakescale_boots", name: "Drakescale Boots", type: "armor", slot: "feet", desc: "Soled with caldera hide — hot sand feels like grass.", def: 12, value: 900, classReq: null },
    { id: "aurora_cloak", name: "Aurora Cloak", type: "armor", slot: "cloak", desc: "Woven from the tundra's night sky.", def: 11, value: 1000, classReq: null, rankReq: "D-" },
    { id: "titan_grips", name: "Titan Grips", type: "armor", slot: "hands", desc: "Gauntlets of a rift sentinel, still humming with starlight.", def: 18, value: 3500, classReq: ["reborn_blade", "lightbringer"], rankReq: "B-" },
    { id: "astral_greaves", name: "Astral Greaves", type: "armor", slot: "feet", desc: "Each step rings like a struck bell in the void.", def: 18, value: 3500, classReq: ["reborn_blade", "lightbringer"], rankReq: "B-" },
    { id: "voidweave_cloak", name: "Voidweave Cloak", type: "armor", slot: "cloak", desc: "A cut of the rift itself; blades slide into nothing.", def: 16, value: 3800, classReq: null, rankReq: "B-" }
  ],

  npcs: [
    { id: "merchant", name: "Marla the Trader", role: "shopkeeper",
      dialogue: ["Fresh gear for a fresh face? You've got the look of someone not from around here.",
                 "Coin talks, stranger. Browse all you like."],
      shopItems: ["worn_dagger", "iron_sword", "cloth_tunic", "leather_vest", "iron_helm", "iron_gauntlets", "iron_boots", "warding_cloak", "power_ring", "minor_potion", "mid_potion", "greater_potion", "mana_potion", "mythril_sword", "mythril_plate", "frost_brand", "seraph_ward", "void_edge", "astral_plate", "mythril_gauntlets", "drakescale_boots", "aurora_cloak", "titan_grips", "astral_greaves", "voidweave_cloak", "sharpening_stone", "iron_tonic", "teleport_scroll", "soul_ledger", "memory_prism", "blessed_ore"] },
    { id: "npc_guide", name: "Elowen the Guide", role: "quest-giver",
      dialogue: ["Ah — you're awake. Do not panic. Yes, this is another world, and yes, I called you here.",
                 "I am Elowen, your Guide. This world needs someone unbound by its old fears. That is you.",
                 "Prove you can survive, clear the woods, and face what sleeps in the ruins. I will walk you through each step."] },
    { id: "npc_storyteller", name: "Old Bram", role: "story",
      dialogue: ["The ruins? Aye, they were here before the town, before the woods even.",
                 "A stone guardian sleeps at their heart. Every age, it wakes when an outsider arrives.",
                 "Folk say the last one to face it never came home. But you... you feel different."] },

    // ---- per-NPC voices (matched by map npc id; role dialogue is the fallback) ----
    { id: "elder", name: "Elder Maro", role: "guild-master",
      dialogue: ["Every legend in Aetheria started with a name on this board.",
                 "Take up to three contracts. Return to me when the work is done, and the guild will remember your deeds."] },
    { id: "oracle", name: "Lost Oracle", role: "story",
      dialogue: ["The river shows me things. It showed me you, weeks before Elowen dared the summoning.",
                 "Two moons pull this world's tide — but a third pull is growing. North, past the fire, where the sky is thinnest.",
                 "Do not fear the ending, outworlder. You are the one piece the ending never accounted for."] },
    { id: "ranger", name: "Woodwatch Ilya", role: "quest-giver",
      dialogue: ["These woods talk, if you stand still long enough. Lately they've been talking about you.",
                 "Mind the deep paths — the pack runs bolder every night, and something in the ruins keeps them stirred."] },
    { id: "ghost_scholar", name: "Bound Scholar", role: "story",
      dialogue: ["I catalogued this place while it drowned. A scholar's habit — dying was no excuse to stop.",
                 "The Golem was our finest work: a gate that judges the hand that knocks. Don't hate it. It is only doing its job.",
                 "If you find any of my pages in the silt... leave them. Some books deserve to stay drowned."] },
    { id: "hakon", name: "Hakon of the Last Watch", role: "story",
      dialogue: ["The watchfire died thirty winters ago. I keep the post because the oath did not.",
                 "Harpies ride the upper gale now. Follow their feathers and you will find the dead king's pass."] },
    { id: "ashsmith", name: "Veya the Ashsmith", role: "story",
      dialogue: ["This forge drinks ember ash and exhales steel. It has been hungry for years.",
                 "Magma Beetles nest below the old bellows. Break their shells and the road to the Cinder Throne will hold."] },
    { id: "star_echo", name: "Echo of Serin", role: "story",
      dialogue: ["I mapped these stars before the rift rearranged them. Now I am the final mark on my own chart.",
                 "Rift Mantas circle the throne road. When their lights go dark, the Nullking will know you are coming."] }
  ],

  storyPhases: [
    { id: 1, numeral: "I",   name: "The Awakened Road", levelMin: 1,  levelMax: 15, mapId: "whispering_woods", color: "#7bd88f" },
    { id: 2, numeral: "II",  name: "Echoes Below",      levelMin: 16, levelMax: 30, mapId: "sunken_ruins",     color: "#b8a17a" },
    { id: 3, numeral: "III", name: "The Frozen Crown",  levelMin: 31, levelMax: 45, mapId: "frostpeak_tundra", color: "#8fc5e8" },
    { id: 4, numeral: "IV",  name: "Tyrant of Embers",  levelMin: 46, levelMax: 60, mapId: "dragon_caldera",   color: "#e27a52" },
    { id: 5, numeral: "V",   name: "The End of Stars",  levelMin: 61, levelMax: 80, mapId: "astral_rift",      color: "#bd8ee8" },
  ],

  quests: [
    { id: "q_awaken", name: "A Strange Awakening", phase: 1, minLevel: 1, giverNpcId: "npc_guide", difficulty: "easy",
      description: "You've woken in a world not your own. Speak with Elowen, then step through the town portal into the Whispering Woods and prove you're able by clearing three slimes.",
      startLines: ["Easy, hero. Breathe — crossing the veil is rougher than it looks. The dizziness passes.",
                   "This is Aetheria. It runs on rules you already know: levels, loot, and things that want to eat you.",
                   "Start small. The portal south leads to the Whispering Woods — clear three slimes and come back alive. I'll be watching."],
      objective: { type: "kill", target: "slime", count: 3 },
      rewards: { exp: 30, zeny: 50, items: ["worn_dagger", "guide_letter"] }, nextQuestId: "q_meet" },
    { id: "q_meet", name: "A Voice by the River", phase: 1, minLevel: 2, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Elowen mentions a lost oracle who keeps to the riverbank in town. Find her and hear what she has to say.",
      startLines: ["You survived the slimes. See? Ten thousand hours of grinding turned out to be a job skill after all.",
                   "There's someone you should meet — the Lost Oracle, down by the riverbank. She saw you coming before I ever cast the summons."],
      objective: { type: "talk", target: "oracle", count: 1 },
      rewards: { exp: 40, zeny: 60, items: ["minor_potion"] }, nextQuestId: "q_market_intro" },
    { id: "q_market_intro", name: "Supplies for the Road", phase: 1, minLevel: 2, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Meet Marla at Moonwell Market and learn where to buy, sell, and restock before following the road deeper.",
      startLines: ["Before you leave town again, meet Marla at the market. A hero without supplies is just a better-dressed ghost.",
                   "She buys your loot and sells potions and gear. Knowing when to restock is part of surviving Aetheria."],
      doneLines: ["Marla has marked the potion shelf for you. The road is dangerous; running out of supplies is optional."],
      objective: { type: "talk", target: "merchant", count: 1 },
      rewards: { exp: 35, zeny: 75, items: ["minor_potion"] }, nextQuestId: "q_guild_intro" },
    { id: "q_guild_intro", name: "A Name on the Board", phase: 1, minLevel: 2, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Meet Elder Maro at the guild hall and learn how repeatable bounties can fund training between story chapters.",
      startLines: ["One more introduction: Elder Maro runs the Adventurer's Guild from the eastern hall.",
                   "His board offers repeatable hunts and deliveries. When the next chapter asks for more levels, the guild keeps your journey moving."],
      doneLines: ["Your name is on the guild ledger now. Take up to three bounties, then return to Maro to claim their rewards."],
      objective: { type: "talk", target: "elder", count: 1 },
      rewards: { exp: 45, zeny: 100, items: ["mid_potion"] },
      // the story forks here per class: each hero proves their calling before q_prove
      nextQuestByClass: { reborn_blade: "q_calling_reborn_blade", drifter: "q_calling_drifter",
        codeweaver: "q_calling_codeweaver", far_shot: "q_calling_far_shot", lightbringer: "q_calling_lightbringer",
        iron_fist: "q_calling_iron_fist", stormcaller: "q_calling_stormcaller" } },
    { id: "q_calling_reborn_blade", name: "Trial of the Shield", phase: 1, minLevel: 3, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Prove a tank's patience: cull four Gel Slimes squatting on the road patrol's route.",
      startLines: ["Every tank guide you ever read said the same thing: hold the line, keep them off the squishy ones.",
                   "Four slimes squat on the road patrol's route. Show me the wall you promised to be."],
      doneLines: ["Not one scratch on the patrol. The guides were right about you."],
      objective: { type: "kill", target: "slime", count: 4 },
      rewards: { exp: 60, zeny: 80, items: ["iron_tonic"] }, nextQuestId: "q_prove" },
    { id: "q_calling_drifter", name: "Trial of the Twin Blades", phase: 1, minLevel: 3, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Prove a courier's speed: cut down three Scrap Goblins before they melt back into the brush.",
      startLines: ["Speed is a courier's currency, and you spent Earth's rush hours buying reflexes.",
                   "Three Scrap Goblins shake down travelers by the road. Be quick — they don't wait."],
      doneLines: ["Three down before the dust settled. The back alleys taught you well."],
      objective: { type: "kill", target: "goblin", count: 3 },
      rewards: { exp: 60, zeny: 80, items: ["sharpening_stone"] }, nextQuestId: "q_prove" },
    { id: "q_calling_codeweaver", name: "Trial of the Arcane", phase: 1, minLevel: 3, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Gather three measures of slime gel — Aetheria's finest debugging paste for sloppy spellwork.",
      startLines: ["Reality here compiles like sloppy code — and slime gel is surprisingly good debugging paste.",
                   "Bring me three globs of Gel Slime residue and I'll show you what a patched spell looks like."],
      doneLines: ["Perfect samples. Try not to think about where the gel has been."],
      objective: { type: "collect", target: "slime_gel", count: 3 },
      rewards: { exp: 60, zeny: 80, items: ["mana_potion"] }, nextQuestId: "q_prove" },
    { id: "q_calling_far_shot", name: "Trial of the Longbow", phase: 1, minLevel: 3, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Prove a marksman's eye: drop three Scrap Goblins before they ever reach you.",
      startLines: ["A target that shoots back is still just a target — that's what you told yourself on the range.",
                   "Three Scrap Goblins haunt the treeline. Thin them out before they ever see you."],
      doneLines: ["Three arrows, three goblins, zero apologies. The range would be proud."],
      objective: { type: "kill", target: "goblin", count: 3 },
      rewards: { exp: 60, zeny: 80, items: ["sharpening_stone"] }, nextQuestId: "q_prove" },
    { id: "q_calling_lightbringer", name: "Trial of the Dawn", phase: 1, minLevel: 3, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Gather three measures of slime gel for the clinic shelf — it binds wounds better than any bandage.",
      startLines: ["You died a healer, and Aetheria noticed. Even its light bends kindly around you.",
                   "Slime gel binds wounds better than any bandage I own. Gather three measures for the clinic shelf."],
      doneLines: ["The clinic shelf is stocked. Some heroes save with a blade — you'll do it twice over."],
      objective: { type: "collect", target: "slime_gel", count: 3 },
      rewards: { exp: 60, zeny: 80, items: ["mid_potion"] }, nextQuestId: "q_prove" },
    { id: "q_calling_iron_fist", name: "Trial of the Hundred Fists", phase: 1, minLevel: 3, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Prove a brawler's rhythm: flatten four Gel Slimes by the river with your bare hands.",
      startLines: ["Frame data, spacing, momentum — you studied fights like scripture. Now your fists are the patch notes.",
                   "Four Gel Slimes bounce by the river. Practice your rhythm on something forgiving."],
      doneLines: ["Clean combos. The slimes never even found their hitstun."],
      objective: { type: "kill", target: "slime", count: 4 },
      rewards: { exp: 60, zeny: 80, items: ["iron_tonic"] }, nextQuestId: "q_prove" },
    { id: "q_calling_stormcaller", name: "Trial of the Storm", phase: 1, minLevel: 3, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Harvest three globs of slime gel — it holds a static charge better than it has any right to.",
      startLines: ["You chased storms across three states. Here, the storms answer when you call.",
                   "Slime gel holds a static charge better than it has any right to. Bring me three globs — prove you can harvest quietly before you thunder."],
      doneLines: ["Charged and bottled. Next time, the sky does the harvesting."],
      objective: { type: "collect", target: "slime_gel", count: 3 },
      rewards: { exp: 60, zeny: 80, items: ["mana_potion"] }, nextQuestId: "q_prove" },
    { id: "q_prove", name: "Prove Yourself", phase: 1, minLevel: 3, giverNpcId: "npc_guide", difficulty: "easy",
      description: "Goblins harass the town road. Cull five of them and gather proof to earn the town's trust.",
      startLines: ["The townsfolk don't trust outsiders. The last 'hero' someone summoned burned half a granary showing off.",
                   "Goblins have been jabbing travelers on the road. Bring me five ears, and the town will start learning your name."],
      doneLines: ["Five ears, and all ten of your own fingers. The guards are already telling stories about you."],
      objective: { type: "collect", target: "goblin_ear", count: 5 },
      rewards: { exp: 80, zeny: 120, items: ["leather_vest", "mid_potion"] }, nextQuestId: "q_pelts" },
    { id: "q_pelts", name: "Winter Is Coming", phase: 1, minLevel: 5, giverNpcId: "npc_guide", difficulty: "normal",
      description: "The town needs warm furs before the cold sets in. Bring Elowen 8 Beast Pelts.",
      startLines: ["Winter here doesn't knock — it kicks the door in. The town needs furs, and the woods are full of wolves.",
                   "Eight pelts. And hero? Wolves won't be as polite as the goblins were."],
      objective: { type: "collect", target: "wolf_pelt", count: 8 },
      rewards: { exp: 220, zeny: 260, items: ["iron_helm"] }, nextQuestId: "q_woods" },
    { id: "q_woods", name: "Clear the Woods", phase: 1, minLevel: 8, giverNpcId: "npc_guide", difficulty: "normal",
      description: "The forest path to the ruins is choked with wolves and shades. Thin the wolf pack so the way is open.",
      startLines: ["The path to the Sunken Ruins is choked by that same pack. Thin it — ten wolves — and the way opens.",
                   "I know: first furs, now culling. Every legend starts as someone's errand list."],
      objective: { type: "kill", target: "wolf", count: 10 },
      rewards: { exp: 160, zeny: 200, items: ["iron_sword", "ancient_seal"] }, nextQuestId: "q_briar" },
    { id: "q_briar", name: "Bristles in the Briar", phase: 1, minLevel: 11, giverNpcId: "npc_guide", difficulty: "normal",
      description: "Thornback Boars have churned the new bramble trail into a killing ground. Drive 6 from the old road.",
      startLines: ["The forest opened another trail, and the boars claimed it before the map ink dried.",
                   "Their thorned hides turn blades. Drive six out, and Ilya can lead us to the old warden."],
      doneLines: ["The briar trail is open. Beyond it, the whole forest is holding its breath."],
      objective: { type: "kill", target: "thornback_boar", count: 6 },
      rewards: { exp: 360, zeny: 320, items: ["mid_potion"] }, nextQuestId: "q_treant" },
    { id: "q_treant", name: "Warden of the Old Road", phase: 1, minLevel: 14, giverNpcId: "npc_guide", difficulty: "hard",
      description: "The Elderwood Treant seals the road beyond the forest. Defeat the ancient guardian and open the route to the Sunken Ruins.",
      startLines: ["The wolves were only fleeing something older. The Elderwood Treant has rooted itself across the northern road.",
                   "Defeat the warden, and the first chapter of your journey ends where the ruins begin."],
      doneLines: ["The old road is breathing again. Beyond it lies the Sunken Ruins — and a harder chapter."],
      objective: { type: "kill", target: "elderwood_treant", count: 1 },
      rewards: { exp: 600, zeny: 500, items: ["iron_boots", "mid_potion"] }, nextQuestId: "q_scout" },

    { id: "q_scout", name: "Scout the Sunken Ruins", phase: 2, minLevel: 16, giverNpcId: "npc_guide", difficulty: "normal",
      description: "Before you face what sleeps in the ruins, set foot inside and see the trial for yourself.",
      startLines: ["Before you swing at what sleeps in the ruins, look at it. Walk in, feel the air, walk out.",
                   "The Oracle calls that place 'the world's first scar'. Set foot inside — that's all I ask. Yet."],
      objective: { type: "explore", target: "sunken_ruins", count: 1 },
      rewards: { exp: 200, zeny: 150, items: ["mid_potion"] }, nextQuestId: "q_shades" },
    { id: "q_shades", name: "Whispers in the Silt", phase: 2, minLevel: 18, giverNpcId: "npc_guide", difficulty: "normal",
      description: "Woodland Shades gather around the drowned halls. Disperse 10 Shades before they overwhelm the ruin road.",
      startLines: ["The ruins noticed you. Shades are gathering in the drowned halls, repeating names no living person remembers.",
                   "Disperse ten. We need the road quiet before you approach its guardian."],
      objective: { type: "kill", target: "shade", count: 10 },
      rewards: { exp: 700, zeny: 450, items: ["mana_potion"] }, nextQuestId: "q_dust" },
    { id: "q_dust", name: "Dust of Lost Memories", phase: 2, minLevel: 22, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Gather 6 handfuls of Shade Dust. The Bound Scholar can use it to reveal the Golem's forgotten seal.",
      startLines: ["The Bound Scholar says Shade Dust remembers the shape of old wards.",
                   "Gather six handfuls. With them, we can wake the Ancient Seal without waking everything else."],
      objective: { type: "collect", target: "shade_dust", count: 6 },
      rewards: { exp: 1100, zeny: 650, items: ["warding_cloak"] }, nextQuestId: "q_drowned" },
    { id: "q_drowned", name: "Choir Beneath the Water", phase: 2, minLevel: 25, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Drowned Acolytes chant around the expanded cloister. Silence 6 before their hymn wakes the Golem early.",
      startLines: ["The new cloister is not empty. Acolytes are chanting below the waterline, and the Golem is answering.",
                   "Silence six. We need the guardian awake on our terms, not theirs."],
      doneLines: ["The drowned hymn has stopped. In the quiet, stone begins to move."],
      objective: { type: "kill", target: "drowned_acolyte", count: 6 },
      rewards: { exp: 950, zeny: 650, items: ["mana_potion"] }, nextQuestId: "q_golem" },
    { id: "q_golem", name: "The Ruin Golem", phase: 2, minLevel: 28, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Use the Ancient Seal to enter the ruins and defeat the Ruin Golem. Face the trial of your arrival.",
      startLines: ["Now the truth. The Golem isn't a monster — it's a lock. It wakes to test every outsider the veil lets through.",
                   "Every summons before you failed its trial. Break the Golem, and Aetheria itself will accept you."],
      doneLines: ["It's done. Do you feel it? The world just... exhaled. It knows you now.",
                  "The last hero never walked out of that chamber. You did. I'm sorry I doubted — no. I'm sorry I ever had reason to."],
      objective: { type: "kill", target: "ruin_golem", count: 1 },
      rewards: { exp: 500, zeny: 600, items: ["guardian_plate"] }, nextQuestId: "q_return" },
    { id: "q_return", name: "Word of the Victory", phase: 2, minLevel: 30, giverNpcId: "npc_guide", difficulty: "easy",
      description: "The golem has fallen. Return to town and tell the Lost Oracle what you saw beneath the ruins.",
      startLines: ["Tell the Oracle what you saw beneath the ruins. Her sight reaches further when someone else's memory holds the lantern."],
      doneLines: ["So her river runs north now. Snow — and a king who never noticed he died. Pack warm, hero."],
      objective: { type: "talk", target: "oracle", count: 1 },
      rewards: { exp: 400, zeny: 300, items: ["greater_potion"] }, nextQuestId: "q_frost" },

    // ===== Expansion arc: north to the peaks, then into the caldera =====
    { id: "q_frost", name: "Into the Frostpeak", phase: 3, minLevel: 31, giverNpcId: "npc_guide", difficulty: "normal",
      description: "A frozen path opened beyond the ruins. Survive the Frostpeak Tundra — cull 12 Frost Wolves.",
      startLines: ["A frozen pass opened beyond the ruins. Frostpeak — where the cold isn't weather, it's a resident.",
                   "Twelve frost wolves hunt that pass. Cull them before they cull the trade road."],
      objective: { type: "kill", target: "frost_wolf", count: 12 },
      rewards: { exp: 900, zeny: 500, items: ["mythril_sword"] }, nextQuestId: "q_hakon" },
    { id: "q_hakon", name: "The Last Watchfire", phase: 3, minLevel: 33, giverNpcId: "npc_guide", difficulty: "normal",
      description: "A lone watchman still guards the widened eastern shelf. Find Hakon of the Last Watch and learn the safe road upward.",
      startLines: ["There is a watchfire on the eastern shelf. It should have gone dark a generation ago.",
                   "Find whoever keeps it burning. Anyone alive that high knows a road the dead have missed."],
      doneLines: ["Hakon's map marks the harpy gale, the ice lake, and one narrow road to the crown."],
      objective: { type: "talk", target: "hakon", count: 1 },
      rewards: { exp: 800, zeny: 450, items: ["greater_potion"] }, nextQuestId: "q_shards" },
    { id: "q_shards", name: "Heart of the Cold", phase: 3, minLevel: 34, giverNpcId: "npc_guide", difficulty: "hard",
      description: "The smiths can temper steel with everlasting ice. Gather 6 Frost Shards from the tundra\'s hunters.",
      startLines: ["The smiths swear steel tempered in everlasting ice can hold against dragonfire. They said it like a dare.",
                   "Six frost shards from the tundra's hunters. Freeze now, forge later."],
      objective: { type: "collect", target: "frost_shard", count: 6 },
      rewards: { exp: 1200, zeny: 700, items: ["warding_cloak"] }, nextQuestId: "q_wraith" },
    { id: "q_wraith", name: "Ghosts of the Peak", phase: 3, minLevel: 38, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Restless wraiths haunt the summit. Banish 6 Ice Wraiths.",
      startLines: ["The wraiths on the summit were climbers once. The mountain kept them.",
                   "Banish six. Think of it as giving them back their names."],
      objective: { type: "kill", target: "ice_wraith", count: 6 },
      rewards: { exp: 1400, zeny: 800, items: ["mythril_plate"] }, nextQuestId: "q_harpy" },
    { id: "q_harpy", name: "Feathers on the Knife-Wind", phase: 3, minLevel: 41, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Rime Harpies control the upper gale. Bring down 5 so Hakon can reopen Revenant Pass.",
      startLines: ["Hakon calls the upper gale a locked door, and the harpies carry its keys.",
                   "Bring down five. When the feathers stop falling, the pass will belong to the living again."],
      doneLines: ["The gale still cuts, but nothing screams inside it now. Revenant Pass is open."],
      objective: { type: "kill", target: "rime_harpy", count: 5 },
      rewards: { exp: 1800, zeny: 1100, items: ["mythril_gauntlets"] }, nextQuestId: "q_revenant" },
    { id: "q_revenant", name: "The Frozen Crown", phase: 3, minLevel: 44, giverNpcId: "npc_guide", difficulty: "elite",
      description: "The Frost Revenant rules the summit. Break the dead king's crown and open the descent into the Dragon Caldera.",
      startLines: ["At the summit waits the Frost Revenant — a king who froze on his throne and never noticed he died.",
                   "Break his crown. The pass into the firelands lies beyond it."],
      doneLines: ["The frozen crown is broken. Below the thawing pass, the mountain glows red."],
      objective: { type: "kill", target: "frost_revenant", count: 1 },
      rewards: { exp: 2600, zeny: 1800, items: ["aurora_cloak", "greater_potion"] }, nextQuestId: "q_caldera" },

    { id: "q_caldera", name: "Descent into Embers", phase: 4, minLevel: 46, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Past the peaks lies a burning caldera. Thin the Ember Imps — defeat 12 of them.",
      startLines: ["Past the peaks, the world turns to fire — the Dragon Caldera. Yes, the name is literal.",
                   "Ember imps breed in the ash like sparks in dry grass. Stamp out twelve before they light the whole slope."],
      objective: { type: "kill", target: "ember_imp", count: 12 },
      rewards: { exp: 2200, zeny: 1200, items: ["frost_brand"] }, nextQuestId: "q_ash" },
    { id: "q_ash", name: "Embers That Never Cool", phase: 4, minLevel: 50, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Ash that never cools can shield against dragonfire. Collect 8 Ember Ash before you face the tyrant.",
      startLines: ["Ash that never cools can shield a body against dragonfire. You are going to want that. Trust me.",
                   "Eight handfuls of ember ash. Then — the tyrant."],
      objective: { type: "collect", target: "ember_ash", count: 8 },
      rewards: { exp: 3000, zeny: 1600, items: ["iron_gauntlets", "greater_potion"] }, nextQuestId: "q_ashsmith" },
    { id: "q_ashsmith", name: "The Forge That Stayed Lit", phase: 4, minLevel: 52, giverNpcId: "npc_guide", difficulty: "normal",
      description: "Smoke rises from an impossible forge on the eastern rim. Find Veya the Ashsmith and ask how to cross the old furnace road.",
      startLines: ["Someone is hammering steel on the eastern rim. Either we found a survivor or the fire learned a trade.",
                   "Find the forgekeeper. Ask what still lives between us and the Cinder Throne."],
      doneLines: ["Veya names the furnace road's true guardians: beetles with shells of living basalt."],
      objective: { type: "talk", target: "ashsmith", count: 1 },
      rewards: { exp: 1800, zeny: 1000, items: ["greater_potion"] }, nextQuestId: "q_stalkers" },
    { id: "q_stalkers", name: "Teeth Beneath the Sand", phase: 4, minLevel: 54, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Sand Stalkers guard the approach to the dragon's lair. Hunt 8 before the final assault.",
      startLines: ["The dragon's lair has another defense: Sand Stalkers beneath every quiet patch of ash.",
                   "Hunt eight and clear a path wide enough for one hero with a very bad idea."],
      objective: { type: "kill", target: "sand_stalker", count: 8 },
      rewards: { exp: 4200, zeny: 2200, items: ["drakescale_boots", "elixir"] }, nextQuestId: "q_beetles" },
    { id: "q_beetles", name: "Shells of the Old Furnace", phase: 4, minLevel: 57, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Magma Beetles are collapsing the furnace road. Break 5 basalt shells before the final assault.",
      startLines: ["The stalkers are gone, but the road itself is moving. Magma Beetles have nested beneath every forge stone.",
                   "Break five shells. Veya will brace the road behind you; your only direction after that is forward."],
      doneLines: ["The furnace road holds. At its end, something vast draws breath."],
      objective: { type: "kill", target: "magma_beetle", count: 5 },
      rewards: { exp: 3600, zeny: 2000, items: ["elixir"] }, nextQuestId: "q_dragon" },
    { id: "q_dragon", name: "The Flame Dragon", phase: 4, minLevel: 60, giverNpcId: "npc_guide", difficulty: "elite",
      description: "The tyrant of the caldera must fall. Slay the Flame Dragon and end its reign.",
      startLines: ["The Flame Dragon has ruled that caldera since before this town had a name. Every year, it takes more.",
                   "This is the fight the world will remember you by. Go end its reign."],
      doneLines: ["You actually did it. The caldera's sky is clear for the first time in living memory.",
                  "But look up, hero. The dragon's fall cracked more than its crown — there's a tear in the sky above the ash, and something older is leaking through."],
      objective: { type: "kill", target: "flame_dragon", count: 1 },
      rewards: { exp: 6000, zeny: 4000, items: ["dawn_edge", "seraph_ward"] }, nextQuestId: "q_rift" },

    // ===== Astral Rift arc: the true endgame =====
    { id: "q_rift", name: "The Tear in the Sky", phase: 5, minLevel: 61, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Beyond the caldera, the world has cracked open. Enter the Astral Rift and scatter 10 Void Wisps.",
      startLines: ["That tear is the Astral Rift — the wound this world has been dying from all along. Now you know why I pulled you across.",
                   "The wisps drifting out of it unmake whatever they touch. Scatter ten. Carefully."],
      objective: { type: "kill", target: "void_wisp", count: 10 },
      rewards: { exp: 8000, zeny: 3000, items: ["void_edge"] }, nextQuestId: "q_echo" },
    { id: "q_echo", name: "The Final Mark on the Map", phase: 5, minLevel: 64, giverNpcId: "npc_guide", difficulty: "hard",
      description: "A cartographer's echo waits beyond the broken star causeway. Find Serin and learn how the rift rearranges itself.",
      startLines: ["A voice is drawing lines in the static beyond the causeway. It calls itself Serin — or what remains of Serin.",
                   "Find the echo. We need a map written by someone the rift already failed to erase."],
      doneLines: ["Serin's last chart shows a road made of moving stars, guarded by things that swim through the sky."],
      objective: { type: "talk", target: "star_echo", count: 1 },
      rewards: { exp: 6500, zeny: 2500, items: ["celestial_draught"] }, nextQuestId: "q_reaver" },
    { id: "q_reaver", name: "The Dead That Walk the Stars", phase: 5, minLevel: 66, giverNpcId: "npc_guide", difficulty: "hard",
      description: "Fallen warriors haunt the rift. Put 8 Star Reavers back to rest.",
      startLines: ["Not everything in the rift is new. Some are heroes who went in before the veil closed — still swinging, long past dead.",
                   "Put eight Star Reavers to rest. And if a blade of starlight looks familiar... don't look too long."],
      objective: { type: "kill", target: "star_reaver", count: 8 },
      rewards: { exp: 12000, zeny: 4000, items: ["astral_plate"] }, nextQuestId: "q_starlight" },
    { id: "q_starlight", name: "Metal from a Dead Sky", phase: 5, minLevel: 70, giverNpcId: "npc_guide", difficulty: "elite",
      description: "Star Iron still hums with the rift\'s power. Gather 6 pieces for the final forging.",
      startLines: ["Star Iron hums with the rift's own power. The smiths need six pieces for the final forging.",
                   "One last errand, hero. I promise."],
      doneLines: ["The forge burns white tonight. Whatever the smiths shape from this, it will be the last thing this world ever needs forged."],
      objective: { type: "collect", target: "star_iron", count: 6 },
      rewards: { exp: 15000, zeny: 5000, items: ["celestial_draught"] }, nextQuestId: "q_knights" },
    { id: "q_knights", name: "Sentinels of the Rift", phase: 5, minLevel: 74, giverNpcId: "npc_guide", difficulty: "elite",
      description: "The Nullking's guard bars the way. Break 8 Astral Knights.",
      startLines: ["The Nullking's sentinels bar the heart of the rift — knights of condensed moonlight, patient as the void.",
                   "Break eight of them, and the way to the throne stands open."],
      objective: { type: "kill", target: "astral_knight", count: 8 },
      rewards: { exp: 18000, zeny: 6000, items: ["astral_glaive"] }, nextQuestId: "q_manta" },
    { id: "q_manta", name: "Lights Above the Throne Road", phase: 5, minLevel: 77, giverNpcId: "npc_guide", difficulty: "elite",
      description: "Rift Mantas patrol the moving star road. Extinguish 5 of their hunting lights before approaching the throne.",
      startLines: ["The knights guarded the gate. The mantas guard the sky above it, and every light is an eye for the king.",
                   "Darken five. Then cross before the constellations learn a new shape."],
      doneLines: ["The throne road goes dark. For the first time, the Nullking cannot see you coming."],
      objective: { type: "kill", target: "rift_manta", count: 5 },
      rewards: { exp: 20000, zeny: 7500, items: ["voidweave_cloak", "elixir"] }, nextQuestId: "q_nullking" },
    { id: "q_nullking", name: "The Crown of Nothing", phase: 5, minLevel: 80, giverNpcId: "npc_guide", difficulty: "elite",
      description: "At the rift's heart waits the Nullking, the end of all things. Unmake the unmaker.",
      startLines: ["At the rift's heart sits the Nullking — the end of all things, wearing a crown.",
                   "Whatever happens in there: thank you. For a world that isn't yours, you gave everything.",
                   "Now go unmake the unmaker."],
      objective: { type: "kill", target: "nullking", count: 1 },
      rewards: { exp: 40000, zeny: 20000, items: ["void_helm", "celestial_draught"] } }
  ],

  // trader crafting: every material gets a second sink beyond refinement/quests.
  // Guard: output resale value must not exceed cost + materials' resale (no zeny minting).
  recipes: [
    { id: "r_sharpening", out: "sharpening_stone", cost: 20, mats: [{ itemId: "wolf_fang", qty: 2 }] },
    { id: "r_tonic", out: "iron_tonic", cost: 20, mats: [{ itemId: "shade_dust", qty: 2 }] },
    { id: "r_greater", out: "greater_potion", cost: 30, mats: [{ itemId: "frost_shard", qty: 2 }, { itemId: "wolf_pelt", qty: 1 }] },
    { id: "r_elixir", out: "elixir", cost: 100, mats: [{ itemId: "ice_core", qty: 1 }, { itemId: "ember_ash", qty: 2 }] },
    { id: "r_celestial", out: "celestial_draught", cost: 200, mats: [{ itemId: "null_core", qty: 1 }, { itemId: "ice_core", qty: 2 }] },
    { id: "r_blessed", out: "blessed_ore", cost: 150, mats: [{ itemId: "star_iron", qty: 2 }, { itemId: "void_shard", qty: 1 }] },
    { id: "r_seraph", out: "seraph_ward", cost: 1500, mats: [{ itemId: "dragon_heart", qty: 1 }, { itemId: "star_iron", qty: 3 }] },
  ],

  // lifetime badges — evaluated against live run state by checkAchievements()
  achievements: [
    { id: "ach_first_blood", icon: "🗡", name: "First Blood", desc: "Slay your first monster.", type: "kills", count: 1 },
    { id: "ach_centurion", icon: "⚔", name: "Centurion", desc: "Slay 100 monsters.", type: "kills", count: 100 },
    { id: "ach_legion", icon: "☠", name: "Legion Slayer", desc: "Slay 1,000 monsters.", type: "kills", count: 1000 },
    { id: "ach_warden", icon: "🌳", name: "Warden of the Woods", desc: "Fell the Elderwood Treant.", type: "guardian", target: "elderwood_treant" },
    { id: "ach_conqueror", icon: "🏰", name: "World Conqueror", desc: "Slay every zone guardian.", type: "guardians", count: 5 },
    { id: "ach_seasoned", icon: "⭐", name: "Seasoned Adventurer", desc: "Reach Base Lv 40.", type: "level", count: 40 },
    { id: "ach_apex", icon: "🌟", name: "Apex of Aetheria", desc: "Reach Base Lv 80.", type: "level", count: 80 },
    { id: "ach_master", icon: "📘", name: "Master of the Craft", desc: "Reach Job Lv 50.", type: "jobLevel", count: 50 },
    { id: "ach_tycoon", icon: "💰", name: "Zeny Tycoon", desc: "Carry 10,000 zeny at once.", type: "zeny", count: 10000 },
    { id: "ach_forge", icon: "🔨", name: "Legend of the Forge", desc: "Refine any equipment to +9.", type: "refine", count: 9 },
    { id: "ach_guild_ace", icon: "🏅", name: "Guild Ace", desc: "Reach guild rank C.", type: "rank", target: "C" },
    { id: "ach_hero", icon: "👑", name: "Hero of Aetheria", desc: "Complete the main story.", type: "story" },
    { id: "ach_reborn", icon: "✦", name: "Twice-Born", desc: "Complete a rebirth.", type: "rebirths", count: 1 },
  ],

  story: {
    intro: [
      "The last thing you remember is the office at midnight — the monitor's glow, one more deadline, your heart stumbling over its own beat.",
      "Then — silence. Grass beneath your fingers. A sky far too blue, with two pale moons.",
      "\"You're awake,\" says a voice. A woman in a green cloak kneels beside you.",
      "\"I am Elowen. I pulled your soul across the veil. I'm sorry — there was no gentler way.\"",
      "\"This world is dying by inches, and its people are too afraid to change it. You are not.\"",
      "You have no idea how to swing a sword. But somehow, you know this is only the beginning."
    ],
    victoryOutro: [
      "The Nullking's crown clatters onto stone that no longer remembers how to be nothing.",
      "Above you, the rift knits itself closed, stitch by starlit stitch, until only sky remains.",
      "Elowen is there — she always is. \"You out-leveled the end of the world itself,\" she laughs, and it almost hides the tremble in her voice.",
      "\"The way home is open now, if you want it. But look at what you built here: a name, a rank, a legend.\"",
      "You look at your hands — calloused from a sword you once didn't know how to hold.",
      "Home can wait a little longer. Aetheria is yours to roam."
    ]
  }
};
