// pixelart.js - original late-16-bit JRPG sprites with a medieval isekai vocabulary.
// Each sprite resolves to a matrix of 1-char pixels; PAL maps chars to colors.
export const PAL = {
  ' ': null, '.': null,               // transparent
  k: '#140a12',                       // hard outline / deepest occlusion
  s: '#f4cfa2', h: '#cf9668',         // skin light / shadow
  w: '#eef5ff', m: '#9eabbc', b: '#606b7b', B: '#343c49', // steel ramp
  r: '#ef744d', R: '#9e3929', O: '#c75f35', // scarlet / oxblood / copper
  u: '#6673e8', U: '#35409b', c: '#96edff', // blue cloth / shadow / magic rim
  g: '#68c57c', G: '#2f7844',         // green wool
  y: '#f2ca59', Y: '#9b7618',         // gold light / shadow
  n: '#8b6739', N: '#51361f', o: '#bd8a4c', L: '#e0ad63', // leather ramp
  p: '#a486dc', q: '#563b91',         // violet cloth / shadow
  i: '#ded3bb', I: '#776c5c',         // undyed wool / shadow
  a: '#a7a7a5', A: '#57595e',         // stone light / shadow
  l: '#65d4f5', z: '#187ca9',         // ice / spectral cyan
  x: '#ffffff', d: '#26151c',         // white flare / dark detail
  f: '#3f7d3a', F: '#2f6a2c', j: '#57a34d', // grass tones
  v: '#2b6ca3', V: '#1d5080', C: '#66a8d8', // water tones
  t: '#b79b6b', T: '#9c8250',         // path
  e: '#6b6f78', E: '#565a62',         // dungeon floor
};

// Source rows may omit trailing transparency. The renderer still receives exact rectangles.
const matrix = (width, height, ...source) => {
  if (source.length !== height) throw new Error(`Pixel matrix expected ${height} rows, got ${source.length}`);
  return source.map((row, y) => {
    if (row.length > width) throw new Error(`Pixel matrix row ${y} exceeds ${width}px`);
    for (const ch of row) if (!(ch in PAL)) throw new Error(`Unknown pixel palette key '${ch}'`);
    return row.padEnd(width, ' ');
  });
};

// Re-house a finished monster drawing on a slightly roomier canvas so motion never
// clips its hard outline. Each pose articulates anchored regions independently:
// torso breathing, alternating lower limbs, then a planted wind-up/front-side lunge.
// Deformation joins are bridged and re-inked so colored materials stay inside hard k.
const monsterMotionSet = source => {
  const sourceWidth = source[0].length;
  const sourceHeight = source.length;
  const width = sourceWidth + 6;
  const height = sourceHeight + 4;
  const painted = [];
  source.forEach((row, y) => {
    for (let x = 0; x < sourceWidth; x++) if (PAL[row[x]]) painted.push({ x, y, ch: row[x] });
  });
  const left = Math.min(...painted.map(pixel => pixel.x));
  const right = Math.max(...painted.map(pixel => pixel.x));
  const top = Math.min(...painted.map(pixel => pixel.y));
  const bottom = Math.max(...painted.map(pixel => pixel.y));
  const center = (left + right) / 2;
  const lowerStart = top + (bottom - top + 1) * 0.72;
  const sourcePixels = new Map(painted.map(pixel => [`${pixel.x},${pixel.y}`, pixel]));

  const pose = ({ torsoX = 0, torsoY = 0, leftLowerX = 0, rightLowerX = 0, frontX = 0 } = {}) => {
    const rows = Array.from({ length: height }, () => Array(width).fill(' '));
    const positions = new Map();
    const place = (x, y, ch) => {
      const current = rows[y][x];
      // Keep material fills when articulated outline pixels overlap them.
      if (current === ' ' || current === 'k' || ch !== 'k') rows[y][x] = ch;
    };
    painted.forEach(pixel => {
      const lower = pixel.y >= lowerStart;
      const lowerX = pixel.x <= center ? leftLowerX : rightLowerX;
      const frontReach = !lower && pixel.x > center
        ? Math.round(frontX * (pixel.x - center) / Math.max(1, right - center))
        : 0;
      const x = pixel.x + 3 + (lower ? lowerX : torsoX + frontReach);
      const y = pixel.y + 2 + (lower ? 0 : torsoY);
      positions.set(`${pixel.x},${pixel.y}`, { x, y });
      place(x, y, pixel.ch);
    });

    // Reconnect neighboring source pixels separated by an articulated joint.
    for (const pixel of painted) {
      const from = positions.get(`${pixel.x},${pixel.y}`);
      for (const [nx, ny] of [
        [pixel.x + 1, pixel.y], [pixel.x, pixel.y + 1],
        [pixel.x - 1, pixel.y + 1], [pixel.x + 1, pixel.y + 1],
      ]) {
        if (!sourcePixels.has(`${nx},${ny}`)) continue;
        const to = positions.get(`${nx},${ny}`);
        const distance = Math.max(Math.abs(to.x - from.x), Math.abs(to.y - from.y));
        for (let step = 1; step < distance; step++) {
          const x = Math.round(from.x + (to.x - from.x) * step / distance);
          const y = Math.round(from.y + (to.y - from.y) * step / distance);
          if (rows[y][x] === ' ') rows[y][x] = 'k';
        }
      }
    }

    // Any newly exposed material edge becomes outline, keeping deformed poses crisp.
    const inked = rows.map(row => [...row]);
    for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) {
      if (!PAL[rows[y][x]] || rows[y][x] === 'k') continue;
      const exposed = [[-1, 0], [1, 0], [0, -1], [0, 1]].some(([dx, dy]) =>
        !PAL[rows[y + dy]?.[x + dx] ?? ' ']);
      if (exposed) inked[y][x] = 'k';
    }
    return matrix(width, height, ...inked.map(row => row.join('')));
  };
  return {
    idle: [pose(), pose({ torsoY: -1 })],
    walk: [
      pose({ torsoY: -1, leftLowerX: -1, rightLowerX: 1 }),
      pose({ leftLowerX: 1, rightLowerX: -1 }),
    ],
    attack: [
      pose({ torsoX: -1, frontX: -1 }),
      pose({ torsoX: 1, torsoY: -1, leftLowerX: -1, frontX: 2 }),
    ],
  };
};

// ---- player classes (16x22, facing down) ----
const player = {
  blade: matrix(16, 22,
    '',
    '      kRk',
    '     krrrk',
    '    kBwwwBk',
    '    kwmwmwk',
    '    kBmmmBk',
    '     ksssk',
    '     ksddk',
    '     kshhk',
    '   kkRrrRkk',
    '  kmkRwyRkmk',
    '  kBkRwwwRBk',
    '  kBkRwywRBk',
    '  kBkRwwwRBk',
    '   kkBmmmkk',
    '    kmyymk',
    '    kmmmmk',
    '    kN  Nk',
    '    kn  nk',
    '    kN  Nk',
    '    kk  kk',
    ''),

  berserker: matrix(16, 22,
    '',
    '    krRrk',
    '   krRRRrk',
    '   kRshsRk',
    '   ksddhsk',
    '   kshhhsk',
    '    khhhk',
    ' kAkkNNNkkAak',
    'kAAkNrrrNkAAak',
    ' kAkNyyyNkAak',
    '  kkNrrrNkk nk',
    '   kNnnnNk  nk',
    '   kNNNNNk  nk',
    '    kNNNk   nk',
    '    kNNNk   kk',
    '    ks sk',
    '    kh hk',
    '   kN   Nk',
    '   kn   nk',
    '   kN   Nk',
    '   kk   kk',
    ''),

  mage: matrix(16, 22,
    '       kyk',
    '      kuyk',
    '     kuuuyk',
    '    kuuuuuyk',
    '   kuuuUuuuuk',
    '   kushhsuuk',
    '   kusddsUuk',
    '   kushhsuuk',
    '    kuuUuuk kyk',
    '   kuuyyuuuk kyk',
    '  kuuUyUuuuukkyk',
    '  kuuuYuuUuuk nk',
    '  kuuuYuuuUuk nk',
    '   kuuYUUuuk  nk',
    '   kuuYuuuuk  nk',
    '    kuYuuuk   nk',
    '    kuuuuuk   kk',
    '     ku uuk',
    '     ku  uk',
    '    kN   Nk',
    '    kk   kk',
    ''),

  ranger: matrix(16, 22,
    '',
    '     kggk',
    '    kgGGgk',
    '   kgGggGgk',
    '   kgshhsgk',
    '   kgsddsgk',
    '   kgshhsgk',
    '    kggggk',
    ' k  kgGGgk  k',
    'knk kggggk kyk',
    'knGkkgyygkkyyk',
    'knGkggGGggk yk',
    'knk kggggk  yk',
    ' k  kgGggk  yk',
    '    kggggk  kk',
    '    kNggNk',
    '    kN  Nk',
    '    kn  nk',
    '   kN    Nk',
    '   kn    nk',
    '   kk    kk',
    ''),

  paladin: matrix(16, 22,
    '     kyYyk',
    '    kywywyk',
    '   kBwwwwwBk',
    '   kwmwmwmwk',
    '   kBwwwwwBk',
    '     ksssk',
    '     ksddk',
    '     kshhk',
    '   kkwyyywkk',
    '  kmkwxYxwmkyk',
    ' kyYkwxxxwkYyk',
    'kyYYkwwywwkYyk',
    'kyYYkwwwwwk nyk',
    ' kyYkBmmmBk nnk',
    '  kkkmwymk  nnk',
    '    kmwwmk  kkk',
    '    kBmmBk',
    '    kN  Nk',
    '    kn  nk',
    '    kY  Yk',
    '    kk  kk',
    ''),

  monk: matrix(16, 22,
    '',
    '     kNNNk',
    '    kNsssNk',
    '    kshhhsk',
    '    ksddhsk',
    '    kshhhsk',
    '     khhhk',
    '   kkiiiiikk',
    '  kskiiiiiksk',
    ' ksskIiyiIkssk',
    ' ksskkiyikkssk',
    '  kskiiiiiksk',
    '   kIiiiiIk',
    '    kiiiyk',
    '    kIiiIk',
    '    kii iik',
    '    ki   ik',
    '    kN  Nk',
    '   kN    Nk',
    '   kn    nk',
    '   kk    kk',
    ''),

  elementalist: matrix(16, 22,
    '      kcyk',
    '     kcccyk',
    '    kuuuuuk',
    '   kuUppUuuk',
    '   kushhsuuk',
    '   kusddsUuk',
    '   kushhsuuk',
    '    kuuUuuk',
    ' kc kpuYupk kr',
    'kcckpuuUupkrrk',
    ' kckpUcucUpkrRk',
    '  kkpuuUuupk kk',
    '   kpUuyUUpk',
    '   kpuuUuupk',
    '    kpuuupk',
    '    kpUUpk',
    '    kpuupk',
    '    kq  qk',
    '    kp  pk',
    '   kq    qk',
    '   kk    kk',
    ''),
};

// ---- NPCs by role (16x16) ----
const npc = {
  shop: matrix(16, 16,
    '     kLLLk',
    '   kkNNNNNkk',
    '    kNsssNk',
    '    kshhhsk',
    '    ksddhsk',
    '    kshhhsk',
    '     khhhk',
    '   kkooooikk',
    '  knkoLyoiknk',
    '  knkooooi knk',
    '  k kIiiiIk k',
    '    kiiyiik',
    '    kIiiIk',
    '    kN  Nk',
    '    kk  kk',
    ''),

  quest: matrix(16, 16,
    '       kLk',
    '    kgggkLk',
    '   kgGGGgkk',
    '   kgshhsgk',
    '   kgsddsgk',
    '   kgshhsgk',
    '    kggggk',
    '  kkgiiyiikk',
    ' knkgiiyiikyk',
    ' knkggGGggkyk',
    '  kkggggggkkk',
    '    kggggk',
    '    kGggGk',
    '    kN  Nk',
    '    kk  kk',
    ''),

  guild: matrix(16, 16,
    '     krRrk',
    '    kBwwwBk',
    '    kwmwmwk',
    '    kBmmmBk',
    '     ksssk',
    '     ksddk',
    '   kkmwywmkk',
    '  kmkmwwwmkmk',
    '  kBkmyyymkBk',
    '  kBkmyRymkBk',
    '   kkBmmmBkk',
    '    kmwwmk',
    '    kBmmBk',
    '    kN  Nk',
    '    kk  kk',
    ''),

  story: matrix(16, 16,
    '     kpppk',
    '    kpqqqpk',
    '    kixxxik',
    '    kishsik',
    '    kisdsik',
    '    kishsik',
    '     kiiik',
    '   kkpyyypkk',
    '  kikpqyqpkik',
    '  kikpppppkik',
    '   kqpiiipqk',
    '    kpiiipk',
    '    kqiiiqk',
    '    kp  pk',
    '    kk  kk',
    ''),
};

// ---- monsters (16x16, bosses 24x24) ----
const monster = {
  // Starter trio are the migration pilots for the six-frame monster contract.
  // Every silhouette keeps a hard outline while body/limb offsets carry the motion.
  slime: {
    idle: [
      matrix(20, 16,
        '',
        '',
        '       kkkkkk',
        '     kkllllllkk',
        '    kllccccclllk',
        '   kllcllllllzllk',
        '  klllcxxlllxxlllk',
        ' kllllcddlllcddllllk',
        'kllllllllllllllllllk',
        'klllzllllllllllzlllk',
        ' kllllllllllllllllk',
        '  kzzllllllllllzzk',
        '   kkzzzzzzzzzzkk',
        '     kkkkkkkkkk',
        '',
        ''),
      matrix(20, 16,
        '',
        '         kk',
        '       kkllkk',
        '     kkllccllkk',
        '    kllccccclllk',
        '   kllcllllllzllk',
        '  klllcxxlllxxlllk',
        ' kllllcddlllcddllllk',
        'kllllllllllllllllllk',
        'klllzllllllllllzlllk',
        'kllllllllllllllllllk',
        ' kzzllllllllllllzzk',
        '  kkzzzzzzzzzzzzkk',
        '    kkkkkkkkkkkk',
        '',
        ''),
    ],
    walk: [
      matrix(20, 16,
        '',
        '',
        '',
        '    kkkkkkkkkkkk',
        '  kkllllccccllllkk',
        ' klllccllllllzzlllk',
        'klllcxxllllxxcllllk',
        'klllcddllllcddlllllk',
        'kllllllllllllllllllk',
        ' klllzllllllllllllk',
        '  kllllllllllllllk',
        '   kzzllllllllzzk',
        '    kkzzzzzzzzkk',
        '      kkkkkkkk',
        '',
        ''),
      matrix(20, 16,
        '',
        '',
        '          kkkk',
        '       kkkllllkk',
        '     kklllccccllk',
        '    kllcllllllzllk',
        '   kllcxxlllxxclllk',
        '  klllcddlllcddllllk',
        ' klllllllllllllllllk',
        'klllzllllllllllllllk',
        'klllllllllllllllllk',
        ' kzzllllllllllllzk',
        '   kzzzzzzzzzzzk',
        '     kkkkkkkkk',
        '',
        ''),
    ],
    attack: [
      matrix(20, 16,
        '',
        '     kkkk',
        '    kllllkk',
        '   kllcccclkk',
        '  kllclllllllkk',
        ' klllcxxlllxxllk',
        ' klllcddlllcddllk',
        '  klllllllllllllk',
        '   kllllllllllllk',
        '    klllzlllllllk',
        '     klllllllllk',
        '      kzzllllzk',
        '       kkzzkk',
        '        kkkk',
        '',
        ''),
      matrix(20, 16,
        '',
        '',
        '',
        '       kkkkkkkkkkk',
        '    kkkllllcccclllkk',
        '  kklllccllllzzllllk',
        ' klllcxxlllxxclllllk',
        'kllllcddlllcddlllllk',
        'kllllllllllllllllllk',
        ' klllzlllllllllllllk',
        '  klllllllllllllllkk',
        '   kzzlllllllllzzk',
        '    kkzzzzzzzzkk',
        '      kkkkkkkk',
        '',
        ''),
    ],
  },

  goblin: {
    idle: [
      matrix(20, 22,
        '',
        '       krrrk',
        '     kkrrRRRrkk',
        '    krRkkkkkRrk',
        '    kk kgggk kk',
        '   kggjgggggjggk',
        '  kGjggGgggGjGgk',
        '  kgydgggggdgygk',
        '  kgggNgggNggggk',
        '   kgggggggggk',
        '   kkGNNNNNGkk',
        ' knkkGoooooGkkyk',
        ' knkGGGGGGGGk kyk',
        '  kk kGggGk  kyk',
        '     kGggGk  kyk',
        '     kG  Gk  kyk',
        '     kg  gk  kk',
        '    kGk  kGk',
        '    kgk  kgk',
        '    kk    kk',
        '',
        ''),
      matrix(20, 22,
        '',
        '        krrrk',
        '      kkrrRRRrkk',
        '     krRkkkkkRrk',
        '     kk kgggk kk',
        '    kggjgggggjggk',
        '   kGjggGgggGjGgk',
        '   kgydgggggdgygk',
        '   kgggNgggNggggk',
        '    kgggggggggk',
        '  kkkkGNNNNNGkkkk',
        ' knk kGoooooGk kyk',
        ' knk kGGGGGGGk kyk',
        '  kk  kGggGk  kyk',
        '      kGggGk  kyk',
        '      kG  Gk  kyk',
        '      kg  gk  kk',
        '     kGk  kGk',
        '     kgk  kgk',
        '     kk    kk',
        '',
        ''),
    ],
    walk: [
      matrix(20, 22,
        '',
        '       krrrk',
        '     kkrrRRRrkk',
        '    krRkkkkkRrk',
        '    kk kgggk kk',
        '   kggjgggggjggk',
        '  kGjggGgggGjGgk',
        '  kgydgggggdgygk',
        '  kgggNgggNggggk',
        '   kgggggggggk',
        '  kkkGNNNNNGkkk',
        ' knkkGoooooGk kyk',
        ' knkGGGGGGGGk kyk',
        '  kk kGggGk  kyk',
        '     kGggGk  kyk',
        '    kGk  kGk kyk',
        '   kGk    kgk kk',
        '   kgk     kGk',
        '   kk      kgk',
        '            kk',
        '',
        ''),
      matrix(20, 22,
        '',
        '        krrrk',
        '      kkrrRRRrkk',
        '     krRkkkkkRrk',
        '     kk kgggk kk',
        '    kggjgggggjggk',
        '   kGjggGgggGjGgk',
        '   kgydgggggdgygk',
        '   kgggNgggNggggk',
        '    kgggggggggk',
        '   kkkGNNNNNGkkk',
        '  kykGoooooGkknk',
        '  kykGGGGGGGGknk',
        '  kyk kGggGk kk',
        '  kyk kGggGk',
        '  kyk kGk  kGk',
        '  kk kgk    kGk',
        '     kGk     kgk',
        '     kgk      kk',
        '     kk',
        '',
        ''),
    ],
    attack: [
      matrix(20, 22,
        '              kNNNk',
        '              kNoNk',
        '              kNNNk',
        '       krrrk    knk',
        '     kkrrRRRrkk knk',
        '    krRkkkkkRrk knk',
        '    kk kgggk kk knk',
        '   kggjgggggjggkknk',
        '  kGjggGgggGjGgkyk',
        '  kgydgggggdgygkyk',
        '  kgggNgggNggggkyk',
        '   kgggggggggk kyk',
        '   kkGNNNNNGkk kyk',
        '    kGoooooGk  kyk',
        '    kGGGGGGGk  kyk',
        '     kGggGk   kk',
        '     kG  Gk',
        '    kGk  kGk',
        '    kgk  kgk',
        '    kk    kk',
        '',
        ''),
      matrix(20, 22,
        '',
        '       krrrk',
        '     kkrrRRRrkk',
        '    krRkkkkkRrk',
        '    kk kgggk kk',
        '   kggjgggggjggk',
        '  kGjggGgggGjGgk',
        '  kgydgggggdgygk',
        '  kgggNgggNggggk',
        '   kgggggggggkkkk',
        '   kkGNNNNNGkNNNk',
        '    kGoooooGkNoNk',
        '    kGGGGGGGkNNNk',
        '     kGggGkkknkk',
        '     kGggGk  knk',
        '     kG  Gk  knk',
        '     kg  gk  kyk',
        '    kGk  kGk kyk',
        '    kgk  kgk  kk',
        '    kk    kk',
        '',
        ''),
    ],
  },

  wolf: {
    idle: [
      matrix(24, 18,
        '',
        '                   kk',
        '                 kkAAk',
        '              kkkAwaaak',
        '     kkk    kkAaaaAAadAk',
        '   kkAwwkkkkAaaaaAaaaAAk',
        '  kAwmaaaaaaaaaaaaaaadAk',
        ' kkAmmAAAAAAAAAaaaaaaaAk',
        'kAAkAAAAAAAAAAAAAAaaaAk',
        ' kk kAaaaAAAAAAAAAAAkk',
        '    kAaaAk kAAAk kAAk',
        '    kAaaAk kAAAk kAak',
        '    kA  Ak kA Ak kA Ak',
        '    kk  kk kk kk kk kk',
        '',
        '',
        '',
        ''),
      matrix(24, 18,
        '',
        '                  kk',
        '                kkAAk',
        '             kkkAwaaak',
        '    kkkk   kkAaaaAAadAk',
        '  kkAwwAkkkAaaaaAaaaAAk',
        ' kAwmaaaaaaaaaaaaaaadAk',
        'kkAmmAAAAAAAAAaaaaaaaAk',
        'kAkAAAAAAAAAAAAAAAaaaAk',
        'kk kAaaaAAAAAAAAAAAAkk',
        '   kAaaAk kAAAk kAAk',
        '   kAaaAk kAAAk kAak',
        '   kA  Ak kA Ak kA Ak',
        '   kk  kk kk kk kk kk',
        '',
        '',
        '',
        ''),
    ],
    walk: [
      matrix(24, 18,
        '',
        '                   kk',
        '                 kkAAk',
        '              kkkAwaaak',
        '    kkkk     kAaaaAAadAk',
        '  kkAwwAkkkkkAaaaaaaaAAk',
        ' kAwmaaaaaaaaaaaaaaaadAk',
        'kkAmmAAAAAAAAAaaaaaaaAk',
        'kAkAAAAAAAAAAAAAAAaaaAk',
        'kk kAaaaAAAAAAAAAAAAkk',
        '  kAaaAk   kAAAk kAAk',
        '  kA Ak     kAak kA Ak',
        ' kk  kk    kAk   kk kk',
        '          kk',
        '',
        '',
        '',
        ''),
      matrix(24, 18,
        '',
        '                  kk',
        '                kkAAk',
        '             kkkAwaaak',
        '      kkk   kAaaaAAadAk',
        '   kkkAwwkkkAaaaaaaaAAk',
        ' kkAwmaaaaaaaaaaaaaadAk',
        'kAAmmAAAAAAAAAaaaaaaaAk',
        'kAkAAAAAAAAAAAAAAAaaaAk',
        'kk kAaaaAAAAAAAAAAAAkk',
        '    kAaaAk kAAAk',
        '    kA Ak  kAak   kAAk',
        '    kk kk   kAk   kA Ak',
        '             kk   kk kk',
        '',
        '',
        '',
        ''),
    ],
    attack: [
      matrix(24, 18,
        '',
        '              kk',
        '            kkAAk',
        '         kkkAwwaaak',
        ' kkkkk kkAaaaaAAadAk',
        'kAwwwAkAaaaaaaaaaAAk',
        ' kAwmmaaaaaaaaaaadAk',
        '  kAmmAAAAAAAAAaaaAk',
        '  kAAAAAAAAAAAAaaaAk',
        '   kAaaaAAAAAAAAAkk',
        '   kAaaAk kAAAk',
        '   kA Ak  kA Ak',
        '   kk kk  kk kk',
        '',
        '',
        '',
        '',
        ''),
      matrix(24, 18,
        '',
        '',
        '                     kk',
        '                   kkAAk',
        '           kkkkkkkAwaaak',
        '   kkkkkkkAaaaaaaaaAadAk',
        '  kkAwwwaaaaaaaaaaaaaAAk',
        'kkAwmmAAAAAAAAAaaaaadAk',
        'kAAkAAAAAAAAAAAAAaaaAk',
        ' kk kAaaaAAAAAAAAAAkk',
        '    kAaaAk  kAAAk',
        '    kA Ak    kA Ak',
        '    kk kk    kk kk',
        '',
        '',
        '',
        '',
        ''),
    ],
  },

  // Batch-2 monsters (boar/shade/leech/acolyte/treant): hand-authored six-frame sets,
  // same idle/walk/attack contract as slime/goblin/wolf. Bases keep each legacy
  // silhouette's material palette; poses articulate anchored regions (planted feet,
  // hood/robe sway, undulating segments, swinging branch-arm) so deltas read at scale.
  thornback_boar: {
    idle: [
      matrix(26, 16,
        '',
        '',
        '      k  k  k',
        '     kGkkGkkGk kkkkk',
        '   k kooooooooknndnk',
        '    koooooooooonnnook',
        '     kooooooooonnnook',
        '     knnnnnnnnnnkkkk',
        '     knnknnnknnk',
        ' kkk knk kNk kNk',
        ' knk knk kNk kNk',
        ' knk knk kNk kNk',
        ' kkk kkk kkk kkk',
        '',
        '',
        ''),
      matrix(26, 16,
        '',
        '      k  k  k',
        '     kGkkGkkGk kkkkk',
        '   k kooooooooknndnk',
        '    koooooooooonnnook',
        '     kooooooooonnnook',
        '     knnnnnnnnnnkkkk',
        '     knnknnnknnk',
        ' kkk knk kNk kNk',
        ' knk knk kNk kNk',
        ' knk knk kNk kNk',
        ' knk knk kNk kNk',
        ' kkk kkk kkk kkk',
        '',
        '',
        ''),
    ],
    walk: [
      matrix(26, 16,
        '',
        '',
        '      k  k  k',
        '     kGkkGkkGk kkkkk',
        '   k kooooooooknndnk',
        '    koooooooooonnnook',
        '     kooooooooonnnook',
        '     knnnnnnnnnnkkkk',
        '     knnknnnknnk',
        ' kkk knk kNk kNk',
        ' knk kkk kkk kNk',
        ' knk         kNk',
        ' knk         kNk',
        ' knk         kNk',
        ' kkk         kkk',
        ''),
      matrix(26, 16,
        '',
        '',
        '      k  k  k',
        '     kGkkGkkGk kkkkk',
        '   k kooooooooknndnk',
        '    koooooooooonnnook',
        '     kooooooooonnnook',
        '     knnnnnnnnnnkkkk',
        '     knnknnnknnk',
        ' kkk knk kNk kNk',
        ' kkk knk kNk kkk',
        '     knk kNk',
        '     knk kNk',
        '     knk kNk',
        '     kkk kkk',
        ''),
    ],
    attack: [
      matrix(26, 16,
        '',
        '',
        '',
        '      k  k  k',
        '     kGkkGkkGkkkkkk',
        '   k koooooooonndnk',
        '    kooooooooonnnook',
        '     koooooooonnnook',
        '     knnnnnnnnnnkkk',
        '     knnknnnknnk',
        ' kkk knk kNk kNk',
        ' knk knk kNk kNk',
        ' kkk kkk kkk kkk',
        '',
        '',
        ''),
      matrix(26, 16,
        '',
        '      k  k  k',
        '     kGkkGkkGk    kkkkk',
        '   k kooooooookk  kndnk',
        '    kooooooooook  knnook',
        '     koooooooook  knnookk',
        '     knnnnnnnnnk  kkkkk',
        '     knnknnnknnk',
        ' kkk knk kNk kNk',
        ' knk knk kNk kNk',
        ' knk knk kNk kNk',
        ' knk knk kkk kNk',
        ' kkk kkk     kNk',
        '             kkk',
        '',
        ''),
    ],
  },

  shade: {
    idle: [
      matrix(18, 17,
        '',
        '',
        '      k',
        '     kqk',
        '    kpppk',
        '   kcpppck',
        '    kpppk',
        '  kkpppppkk',
        '  kppppppck',
        '  kppppppck',
        '  kqqqqqqqk',
        '  kkqqkqqkk',
        '    kk kk kk',
        '    kk kk kk',
        '    kk kk kk',
        '       kk',
        ''),
      matrix(18, 17,
        '',
        '      k',
        '     kqk',
        '    kpppk',
        '   kcpppck',
        '    kpppk',
        '  kkpppppkk',
        '  kppppppck',
        '  kppppppck',
        '  kqqqqqqqk',
        '  kqqkqqqqk',
        '   kk kqqk',
        '   kk kqqk',
        '   kk kqkk',
        '      kk',
        '',
        ''),
    ],
    walk: [
      matrix(18, 17,
        '',
        '',
        '       k',
        '      kqk',
        '     kpppk',
        '    kcpppck',
        '     kpppk',
        '   kkpppppkk',
        '   kppppppck',
        '   kppppppck',
        '   kqqqqqqqk',
        '   kqqqqqqkk',
        '    kqqqqk',
        '    kqqqqk',
        '    kkqqkk',
        '      kk',
        ''),
      matrix(18, 17,
        '',
        '       k',
        '      kqk',
        '     kpppk',
        '    kcpppck',
        '     kpppk',
        '   kkpppppkk',
        '   kppppppck',
        '   kppppppck',
        '   kqqqqqqqk',
        '   kkkqqkkqk',
        '      kk  kk  kk',
        '      kk  kk  kk',
        '      kk  kk  kk',
        '          kk',
        '',
        ''),
    ],
    attack: [
      matrix(18, 17,
        '',
        '',
        '     k',
        '    kqk',
        '   kpppk',
        '  kcpppck',
        '   kpppk',
        ' kkpppppkk',
        ' kppppppck',
        ' kppppppck',
        ' kqqqqqqqk',
        ' kkqqkqqkk',
        '   kk kk kk',
        '   kk kk kk',
        '   kk kk kk',
        '      kk',
        ''),
      matrix(18, 17,
        '',
        '       k',
        '      kqk',
        '     kpppk',
        '    kcpppck',
        '     kpppk',
        '   kkpppppkkkkkkk',
        '   kppppppcpkkkkk',
        '   kppppppck',
        '   kqqqqqqqk',
        '   kkqqkqqkk',
        '     kk kk kk',
        '     kk kk kk',
        '     kk kk kk',
        '        kk',
        '',
        ''),
    ],
  },

  mire_leech: {
    idle: [
      matrix(25, 9,
        '',
        '           kkk     kkk',
        '        kkkgggkkk  kgk',
        '  kkkkkkGGGjggGGGkkgdk',
        '  kGGgggGGGgggGGGgggdk',
        '  kkkggjGGGkkkGGGgggdk',
        '     kkkkkk   kkkggggk',
        '                 kkkkk',
        ''),
      matrix(25, 9,
        '',
        '     kkk         kkkkk',
        '     kggkkk   kkkggggk',
        '  kkkgggGGGkkkGGGgggdk',
        '  kGGgkkGGGgggGGGgggdk',
        '  kkkk  kGGgggGGGkkgdk',
        '        kkkgggkkk  kgk',
        '           kkk     kkk',
        ''),
    ],
    walk: [
      matrix(25, 9,
        '',
        '          kkk     kkk',
        '       kkkgggkkk  kgk',
        ' kkkkkkGGGjggGGGkkgdk',
        ' kGGgggGGGgggGGGgggdk',
        ' kkkggjGGGkkkGGGgggdk',
        '    kkkkkk   kkkggggk',
        '                kkkkk',
        ''),
      matrix(25, 9,
        '',
        '      kkk         kkkkk',
        '      kggkkk   kkkggggk',
        '   kkkgggGGGkkkGGGgggdk',
        '   kGGgkkGGGgggGGGgggdk',
        '   kkkk  kGGgggGGGkkgdk',
        '         kkkgggkkk  kgk',
        '            kkk     kkk',
        ''),
    ],
    attack: [
      matrix(25, 9,
        '',
        '           kkk     kkk',
        '        kkkgggkkk  kdk',
        '  kkkkkkGGGjggGGGkkgdk',
        '  kGGgggGGGgggGGGgggdk',
        '  kkkggjGGGkkkGGGgggdk',
        '     kkkkkk   kkkgggdk',
        '                 kkkkk',
        ''),
      matrix(25, 9,
        '',
        '     kkk           kkkkk',
        '     kggkkk     kkkgggdk',
        '  kkkgggGGGkkk  kGGgggdk',
        '  kGGgkkGGGggk  kGGgggdk',
        '  kkkk  kGGggk  kGGkkgdk',
        '        kkkggk  kkk  kdk',
        '           kkk       kkk',
        ''),
    ],
  },

  drowned_acolyte: {
    idle: [
      matrix(11, 19,
        '',
        '',
        '',
        '        k',
        '        k',
        '   kkkk k',
        '   kvvk k',
        '   kddk k',
        '   kdVVkk',
        ' kkvvvvvk',
        ' kCvvvvvk',
        ' kvvvvvvk',
        ' kVVVVVVk',
        ' kVVVVVVk',
        ' kVVVVVVk',
        '  kVVVVk',
        '  kkVVkk',
        '    kk',
        ''),
      matrix(11, 19,
        '',
        '',
        '        k',
        '        k',
        '   kkkk k',
        '   kvvk k',
        '   kddk k',
        '   kdVVkk',
        ' kkvvvvvk',
        ' kCvvvvvk',
        ' kvvvvvvk',
        ' kVVVVVVk',
        ' kVVVVVVk',
        ' kVkkVVkk',
        ' kk  kk',
        ' kk  kk',
        '     kk',
        '',
        ''),
    ],
    walk: [
      matrix(11, 19,
        '',
        '',
        '',
        '         k',
        '         k',
        '    kkkk k',
        '    kvvk k',
        '    kddk k',
        '    kdVVkk',
        '  kkvvvvvk',
        '  kCvvvvvk',
        '  kvvvvvvk',
        '  kVVVVVVk',
        '  kVVVVVVk',
        '  kVkkVVkk',
        '  kk  kk',
        '  kk  kk',
        '      kk',
        ''),
      matrix(11, 19,
        '',
        '',
        '         k',
        '         k',
        '    kkkk k',
        '    kvvk k',
        '    kddk k',
        '    kdVVkk',
        '  kkvvvvvk',
        '  kCvvvvvk',
        '  kvvvvvvk',
        '  kVVVVVVk',
        '  kVVVVVVk',
        '  kkVVkkVk',
        '    kk  kk',
        '    kk  kk',
        '    kk',
        '',
        ''),
    ],
    attack: [
      matrix(11, 19,
        '',
        '',
        '        k',
        '        k',
        '        k',
        '   kkkk k',
        '   kvvk k',
        '   kddVkk',
        '   kdVVvk',
        ' kkvvvvvk',
        ' kCvvvvvk',
        ' kvvvvvvk',
        ' kVVVVVVk',
        ' kVVVVVVk',
        ' kVVVVVVk',
        '  kVVVVk',
        '  kkVVkk',
        '    kk',
        ''),
      matrix(11, 19,
        '',
        '         k',
        '         k',
        '         k',
        '         k',
        '    kkkkkk',
        '    kvvVvk',
        '    kddVvk',
        '    kwVVvk',
        '  kkvvvvvk',
        '  kCvvvvvk',
        '  kvvvvvvk',
        '  kVVVVVVk',
        '  kVVVVVVk',
        '  kVVVVVVk',
        '   kVVVVk',
        '   kkVVkk',
        '     kk',
        ''),
    ],
  },
  gilded_ravager: monsterMotionSet(matrix(24, 24,
    '', '',
    '        kkYYkk',
    '       kYyyyyYk',
    '       kyOOOOyk',
    '       kyOrrOyk',
    '       kYyyyyYk',
    '    kkkkYYyyYYkkkk',
    '  kkYYkkYyyyyYkkYYkk',
    ' kYyyYkkyywwyykkYyyYk',
    ' kYyYYkkyyOOyykYYyYYk',
    ' kYyyyYkYyrRryYkYyyyYk',
    '  kYYYkkyyyyyykkYYYk',
    '   kkk kYyyYyYk kkk',
    '       kYyYyYk',
    '       kYyyyYk',
    '       kyYYyyk',
    '      kkYyyYkk',
    '     kYYk  kYYk',
    '     kYyk  kYyk',
    '     kYYk  kYYk',
    '     kkkk  kkkk',
    '', '')),

  ruin_golem: monsterMotionSet(matrix(24, 24,
    '', '',
    '        kkAAkk',
    '       kAaaaaAk',
    '       kaYYYYak',
    '       kaYrrYak',
    '       kAaaaaAk',
    '    kkkkAAaaAAkkkk',
    '  kkAAkkAaaaaAkkAAkk',
    ' kAaaAkkaawwaakkAaaAk',
    ' kAaAAkkaammaakAAaAAk',
    ' kAaaaAkAayYyaAkAaaaAk',
    '  kAAAkkaaaaaakkAAAk',
    '   kkk kAaaAaAk kkk',
    '       kAaAaAk',
    '       kAaaaAk',
    '       kaAAaak',
    '      kkAaaAkk',
    '     kAAk  kAAk',
    '     kAak  kAak',
    '     kAAk  kAAk',
    '     kkkk  kkkk',
    '', '')),

  frost_wolf: monsterMotionSet(matrix(16, 16,
    '',
    ' kk         kk',
    'kzk        kzzk',
    'kzzkk    kkzzzk',
    'kzlzzkkkkzzzzzk',
    ' kzzxllllllllzk',
    ' kzdlcllllcldzk',
    'kzlllllllllllzk',
    'kzlcllllllllzzk',
    ' kkzzllllllzzk',
    '  kzk kk kzzk',
    '  kzk kk kzzk',
    '  kk  kk  kk',
    '', '', '')),

  ice_wraith: monsterMotionSet(matrix(16, 16,
    '',
    '      kkk',
    '    kklclkk',
    '   klllllllzk',
    '  kllxlllxllzk',
    '  klldllldllzk',
    ' klllllllllllzk',
    'kllzkllllkzllzk',
    ' klllllllllllzk',
    '  kzlllllllzzk',
    '   kzlcllzzk',
    '   klkllklk',
    '   kk kk kk',
    '      k',
    '', '')),

  rime_harpy: monsterMotionSet(matrix(16, 16,
    '      kck',
    '     kclck',
    ' kk  klllk  kk',
    'kzzkklddlkkzzk',
    ' kzlllllllzzk',
    '  kzlclcllzk',
    '   kllllllk',
    '  kkzllllzkk',
    ' kzk kllk kzk',
    'kk   kllk   kk',
    '     kzlk',
    '     kllk',
    '    kzk kzk',
    '    kk   kk',
    '', '')),

  sand_stalker: monsterMotionSet(matrix(16, 16,
    '',
    '  kk       kk',
    ' kLNk     kNLk',
    ' kLoNkkkkkNoLk',
    '  kLoooooooLk',
    ' kLoLoooooLoLk',
    'koodooooooodook',
    'koooNNNNNoooook',
    ' kLooLyoLooLk',
    '  kNNNNNNNNk',
    '  knoNNNNonk',
    ' kk kN Nkk kk',
    'knk ko ok knk',
    'kk  kk kk  kk',
    '', '')),

  ember_imp: monsterMotionSet(matrix(16, 16,
    '  kr         rk',
    '  kRrk     krRk',
    '   krkkkkkrrk',
    '   kRrrrrrRk',
    '  krOrrrrrOrk',
    '  krrdrrrdrrk',
    '  krrryyrrrrk',
    ' kRrrrrrrrrRk',
    'krRkRRRRRRkRrk',
    ' kk kRrrRk kk',
    '    kRyyRk',
    '    kRrrRk',
    '    kr  rk',
    '    kk  kk',
    '', '')),

  magma_beetle: monsterMotionSet(matrix(16, 16,
    '',
    '   kk    kk',
    '  kRrkkkkRrk',
    ' kRROrrrrORRk',
    'kRRRROOORRRRk',
    'kROrryyyyrrORk',
    'kRRrrddddrrRRk',
    ' kRROrrrrORRk',
    '  kRRROORRRk',
    ' kk kRrrRk kk',
    'kRk kRrrRk kRk',
    'kk  kk  kk  kk',
    '', '', '', '')),

  flame_dragon: monsterMotionSet(matrix(24, 24,
    '',
    '           kRk',
    '      kk  krRrk  kk',
    '    krrRkkrRRRrkkRrrk',
    '   krRRRRRRROORRRRRRrk',
    '  krRyyRRRrrrrRRRyyRRrk',
    '  kRyyyRRrdrrdRRRyyyRRk',
    '   kRRRRRrrrrrrRRRRRRk',
    '    kkrRRROOORRRRrkk',
    '      krRRRRRRRrk',
    '   kkkrROyyyyORrkkk',
    '  kRrkkRrrrrrrRkkRrk',
    ' krRk kRRROORRRk kRrk',
    ' kRk  krRRRRRRrk  kRk',
    ' kk   kRRROORRRk   kk',
    '      krRRRRRRrk',
    '      kRROOORRk',
    '     kRRRk kRRRk',
    '    krRrk   krRrk',
    '    kRrk     kRrk',
    '    kkk       kkk',
    '', '', '')),

  void_wisp: monsterMotionSet(matrix(16, 16,
    '',
    '       kk',
    '     kkppkk',
    '    kppqqppk',
    '   kppcxxcppk',
    '  kqppcxxcppqk',
    '  kppppccppppk',
    '   kqppppppqk',
    '    kqppppqk',
    '     kkppkk',
    '   kk  kk  kk',
    '  kppk kq kppk',
    '   kk     kk',
    '', '', '')),

  star_reaver: monsterMotionSet(matrix(16, 16,
    '      kppk',
    '     kpqppk',
    '    kBwwwBkk',
    '    kwdwdwk yk',
    '    kBmmmBk wyk',
    '   kkqpppqkkwk',
    '  kBkqpypqkBwk',
    '  kmkqpppqkmwk',
    '  kBkqpppqkByk',
    '   kkqpppqkk k',
    '    kqpppqk',
    '    kBppBk',
    '    kq  qk',
    '    kp  pk',
    '    kk  kk',
    '')),

  astral_knight: monsterMotionSet(matrix(16, 16,
    '     kpppk',
    '    kBwwwBk',
    '    kwcwcwk',
    '    kBmmmBk',
    '   kkwwwwwkk',
    '  kmkwcpcwkmk',
    '  kBkwwpwwkBk',
    '  kBkwwpwwkBk',
    '   kkwwpwwkk',
    '    kBmmmBk',
    '    kmwwwmk',
    '    kBmmBk',
    '    kq  qk',
    '    kp  pk',
    '    kk  kk',
    '')),

  rift_manta: monsterMotionSet(matrix(16, 16,
    '', '',
    '       kk',
    '    kkkppkkk',
    '  kkqppccppqkk',
    ' kqpppcxxcpppqk',
    'kqppppcddcppppqk',
    ' kpqqppccppqqpk',
    '  kkqppppppqkk',
    '    kqppppqk',
    '     kpqqpk',
    '     kq  qk',
    '      k  k',
    '', '', '')),

  elderwood_treant: {
    idle: [
      matrix(23, 29,
        '',
        '       k',
        '     kkGk',
        '    kggGGk      k',
        '   kggggGGk    kgk',
        '  kggggggggk  kgggk',
        ' kggggggggggk  kgk',
        ' kgggggggggggk kgk',
        '  kgggggggggggknnk',
        '   kgggggggggk knk',
        '    kgGGggggkNknkk',
        '     kGGGggk kNk',
        '    koooook  kNk',
        ' kkknoooook  kNk',
        ' knnnooooonkkkkk',
        ' knnnooxoonnk',
        ' knnnoNxNonnk',
        ' kkknoNNNonkk',
        '    kodNNok',
        '    koNNNok',
        '    koNNNok',
        '    koNNNok',
        '     kNNnnk',
        '     kNNnnk',
        '     kNNnnk',
        '     kkkkkk',
        '',
        '',
        ''),
      matrix(23, 29,
        '',
        '     k kkk',
        '    kgkGGGk     k',
        '   kggggGGGk   kgk',
        '  kggggggGggk kgggk',
        ' kgggggggggggk kgk',
        '  kgggggggggggkngk',
        '   kgggggggggggnnk',
        '    kggGgggggggnnk',
        '     kGGGggggNNnkk',
        '      kGGGggkNNk',
        '    kkoooonk kNk',
        ' kkknoooook  kNk',
        ' knnnooooonkkkkk',
        ' knnnooxoonnk',
        ' knnnoNxNonnk',
        ' kkknoNNNonkk',
        '    kodNNok',
        '    koNNNok',
        '    koNNNok',
        '    koNNNok',
        '     kNNnnk',
        '     kNNnnk',
        '     kNNnnk',
        '     kkkkkk',
        '',
        '',
        '',
        ''),
    ],
    walk: [
      matrix(23, 29,
        '',
        '       k',
        '     kkGk',
        '    kggGGk      k',
        '   kggggGGk    kgk',
        '  kggggggggk  kgggk',
        ' kggggggggggk  kgk',
        ' kgggggggggggk kgk',
        '  kgggggggggggknnk',
        '   kgggggggggk knk',
        '    kgGGggggkNknkk',
        '     kGGGggk kNk',
        '    koooook  kNk',
        ' kkknoooook  kNk',
        ' knnnooooonkkkkk',
        ' knnnooxoonnk',
        ' knnnoNxNonnk',
        ' kkknoNNNonkk',
        '    kodNNok',
        '    koNNNok',
        '    koNNNok',
        '    koNNNok',
        '     kNNnnk',
        '     kNNkkk',
        '     kNk',
        '     kNk',
        '     kNk',
        '     kkk',
        ''),
      matrix(23, 29,
        '',
        '       k',
        '     kkGk',
        '    kggGGk      k',
        '   kggggGGk    kgk',
        '  kggggggggk  kgggk',
        ' kggggggggggk  kgk',
        ' kgggggggggggk kgk',
        '  kgggggggggggknnk',
        '   kgggggggggk knk',
        '    kgGGggggkNknkk',
        '     kGGGggk kNk',
        '    koooook  kNk',
        ' kkknoooook  kNk',
        ' knnnooooonkkkkk',
        ' knnnooxoonnk',
        ' knnnoNxNonnk',
        ' kkknoNNNonkk',
        '    kodNNok',
        '    koNNNok',
        '    koNNNok',
        '    koNNNok',
        '     kNNnnk',
        '     kkknnk',
        '        knk',
        '        knk',
        '        knk',
        '        kkk',
        ''),
    ],
    attack: [
      matrix(23, 29,
        '',
        '       k      kkk',
        '     kkGk    kgggk',
        '    kggGGk    kgk',
        '   kggggGGk   kgk',
        '  kggggggggk  knk',
        ' kggggggggggk knk',
        ' kgggggggggggknnk',
        '  kggggggggggNNk',
        '   kgggggggggNNk',
        '    kgGGggggkNNk',
        '     kGGGggk kNk',
        '    koooook  kNk',
        ' kkknoooook  kNk',
        ' knnnooooonkkkkk',
        ' knnnooxoonnk',
        ' knnnoNxNonnk',
        ' kkknoNNNonkk',
        '    kodNNok',
        '    koNNNok',
        '    koNNNok',
        '    koNNNok',
        '     kNNnnk',
        '     kNNnnk',
        '     kNNnnk',
        '     kkkkkk',
        '',
        '',
        ''),
      matrix(23, 29,
        '',
        '        k',
        '     k kGk',
        '    kgkGGGk',
        '   kggggGGGk',
        '  kggggggGggk      k',
        ' kgggggggggggk    kgk',
        '  kgggggggggggk  kgggk',
        '   kgggggggggggk  kgk',
        '    kggGggggggk   kgk',
        '     kGGGggggk    knk',
        '      kGGGggk     knk',
        '    kkoooonk kkk  kkk',
        ' kkknoooook  kNk',
        ' knnnooooonkkkkk',
        ' knnnooxoonnk',
        ' knnnoNxNonnk',
        ' kkknoNNNonkk',
        '    kodNNok',
        '    koNNNok',
        '    koNNNok',
        '    koNNNok',
        '     kNNnnk',
        '     kNNnnk',
        '     kNNnnk',
        '     kkkkkk',
        '',
        '',
        ''),
    ],
  },
  frost_revenant: monsterMotionSet(matrix(24, 24,
    '',
    '        kc c ck',
    '       kclclclck',
    '       klllllllk',
    '      klzzlzzllk',
    '     kllxlllxlllk',
    '     klldllldlllzk',
    '      kllllllllk',
    '    kkkzlllllzkkk',
    '   kzlllllllllllzk',
    '  kllzklllllllzkllk',
    '  klzk klllllk kzlk',
    '  kck  kzlllzk  kck',
    '   k   klllllk   k',
    '       kzlllzk',
    '       klllllk',
    '      kzlllllzk',
    '      kllk kllk',
    '      klk   klk',
    '      kk     kk',
    '', '', '', '')),

  nullking: monsterMotionSet(matrix(24, 24,
    '',
    '        kyYyYyk',
    '       kyYYYYYyk',
    '        kqqqqqk',
    '       kqpppppqk',
    '      kqpcxxcppqk',
    '      kqpdddddpqk',
    '      kqpppppppqk',
    '    kkqppqppqppqkk',
    '   kppkqpppppqkppk',
    '  kqppkkqpppqkkppqk',
    '  kppk kqpppqk kppk',
    '  kqk  kqqpqqk  kqk',
    '   k   kqpppqk   k',
    '       kqpppqk',
    '       kqpqpqk',
    '       kqpppqk',
    '       kqk kqk',
    '       kpk kpk',
    '       kk   kk',
    '', '', '', '')),
};

// ---- player WALK frames: cloth, weapon and stance all shift with the step ----
const walkFrame = (base, replacements) => matrix(
  base[0].length,
  base.length,
  ...base.map((row, index) => replacements[index] ?? row),
);
const playerWalk = {
  blade: walkFrame(player.blade, {
    10: ' kmkRwyRkmk', 11: ' kBkRwwwRBk', 14: '  kkBmmmkk', 15: '   kmyymk',
    16: '   kmmmmk', 17: '   kN   Nk', 18: '  kn     nk', 19: '  kN     Nk', 20: '  kk     kk',
  }),
  berserker: walkFrame(player.berserker, {
    8: ' kAAkNrrrNkAAak', 9: 'kAAkNyyyNkAak', 13: '   kNNNk   nk', 14: '   kNNNk   kk',
    15: '   ks  sk', 16: '   kh  hk', 17: '  kN    Nk', 18: ' kn      nk', 19: ' kN      Nk', 20: ' kk      kk',
  }),
  mage: walkFrame(player.mage, {
    10: ' kuuUyUuuuukkyk', 11: ' kuuuYuuUuuk nk', 14: '  kuuYuuuuk  nk', 15: '   kuYuuuk   nk',
    16: '   kuuuuuk   kk', 17: '    ku  uuk', 18: '    ku   uk', 19: '   kN    Nk', 20: '   kk    kk',
  }),
  ranger: walkFrame(player.ranger, {
    9: 'knk kggggkkyk', 10: 'knGkkgyygk yyk', 12: 'knk kggggk yk', 14: '   kggggk  kk',
    15: '   kNggNk', 16: '   kN   Nk', 17: '  kn     nk', 18: '  kN     Nk', 19: '  kn     nk', 20: '  kk     kk',
  }),
  paladin: walkFrame(player.paladin, {
    10: 'kyYkwxxxwkYyk', 11: 'kyYYkwwywwkYyk', 13: 'kyYkBmmmBk nnk', 14: ' kkkmwymk  nnk',
    15: '   kmwwmk  kkk', 16: '   kBmmBk', 17: '   kN   Nk', 18: '  kn     nk', 19: '  kY     Yk', 20: '  kk     kk',
  }),
  monk: walkFrame(player.monk, {
    8: ' kskiiiiiksk', 9: 'ksskIiyiIkssk', 11: ' kskiiiiiksk', 13: '   kiiiyk',
    14: '   kIiiIk', 15: '   kii  iik', 16: '   ki    ik', 17: '   kN   Nk', 18: '  kN     Nk', 19: '  kn     nk', 20: '  kk     kk',
  }),
  elementalist: walkFrame(player.elementalist, {
    8: 'kcc kpuYupk kr', 9: ' kckpuuUupkrrk', 10: '  kpUcucUpkrRk', 13: '  kpuuUuupk',
    14: '   kpuuupk', 15: '   kpUUpk', 16: '   kpuupk', 17: '   kq   qk', 18: '  kp     pk', 19: '  kq     qk', 20: '  kk     kk',
  }),
};

// ---- 16x16 item / equipment icons ----
const item = {
  sword: matrix(16, 16,
    '       kwk',
    '      kwxk',
    '      kwmk',
    '      kwmk',
    '      kwmk',
    '      kwmk',
    '     kwwmk',
    '    kBwwwmk',
    '   kykkYkkyk',
    '      kLk',
    '      kNk',
    '      kLk',
    '      kkk',
    '', '', ''),

  dagger: matrix(16, 16,
    '       kk',
    '      kwk',
    '      kwk',
    '     kwmk',
    '     kwmk',
    '    kBwmk',
    '   kykkYk',
    '      kLk',
    '      kNk',
    '      kk',
    '', '', '', '', '', ''),

  greatsword: matrix(16, 16,
    '      kwwk',
    '     kwxwmk',
    '     kwywmk',
    '     kwywmk',
    '     kwywmk',
    '     kwywmk',
    '     kwywmk',
    '    kBwyywmk',
    '  kyYkkwYwkkYyk',
    '      kLLk',
    '      kNNk',
    '      kLLk',
    '       kk',
    '', '', ''),

  tunic: matrix(16, 16,
    '', '',
    '   kk     kk',
    '  kiikiiiikik',
    ' kiiikiiiikiiik',
    ' kIiiiiiiiiiIik',
    '  kIiiiiiiiIk',
    '   kiiiyiiik',
    '   kiiiiiiiik',
    '   kIiiiiiIik',
    '    kkkkkkk',
    '', '', '', '', ''),

  vest: matrix(16, 16,
    '', '',
    '   kk     kk',
    '  kNLkNNNkLNk',
    ' kNLLkNNNkLLNk',
    ' kNNNkNyNkNNNk',
    '  kNNkNyNkNNk',
    '   kNkNyNkNk',
    '   kNkNNNkNk',
    '   kNNNNNNNk',
    '    kkkkkkk',
    '', '', '', '', ''),

  plate: matrix(16, 16,
    '',
    '     kwwwk',
    '   kkBmmmBkk',
    '  kmkwmwmkmk',
    ' kBmkwwwwwkmBk',
    ' kBmkwwywwkmBk',
    '  kmkwwwwwkmk',
    '   kBmwymBk',
    '   kmwwwwmk',
    '   kBmmmmBk',
    '    kkkkkk',
    '', '', '', '', ''),

  potred: matrix(16, 16,
    '',
    '      kkk',
    '     kwmwk',
    '      kkk',
    '     kwwwk',
    '    kwxwwmk',
    '   kwrrrrwmk',
    '   kwrOrrwmk',
    '   kwrRRrwmk',
    '   kwrrrrwmk',
    '    kmwwmk',
    '     kkkk',
    '', '', '', ''),

  potblue: matrix(16, 16,
    '',
    '      kkk',
    '     kwmwk',
    '      kkk',
    '     kwwwk',
    '    kwxwwmk',
    '   kwuuuuwmk',
    '   kwucUuwmk',
    '   kwuUUuwmk',
    '   kwuuuuwmk',
    '    kmwwmk',
    '     kkkk',
    '', '', '', ''),

  gem: matrix(16, 16,
    '', '',
    '       kk',
    '      kcck',
    '     kcllzk',
    '    kcllllzk',
    '   kclxllllzk',
    '    klllllzk',
    '     klllzk',
    '      klzk',
    '       kk',
    '', '', '', '', ''),

  scroll: matrix(16, 16,
    '', '',
    '   kkkkkkkkk',
    '  kiiiiiiiiik',
    '  kixkykkyiik',
    '  kikyYyYkiik',
    '  kikyRyYkiik',
    '  kixkykkyiik',
    '  kIiiiiiiiIk',
    '   kkkkkkkkk',
    '', '', '', '', '', ''),

  core: matrix(16, 16,
    '',
    '       kk',
    '     kkyykk',
    '    kyROORyk',
    '   kyRrrrrRyk',
    '   kRrrccrrRk',
    '   kRrcxxcrRk',
    '   kRrrccrrRk',
    '    kyROORyk',
    '     kkyykk',
    '       kk',
    '', '', '', '', ''),

  helm: matrix(16, 16,
    '', '',
    '     kwwwk',
    '   kkBmmmBkk',
    '  kBwwwwwwwBk',
    '  kwmwmwmwmwk',
    '  kBwwywywwBk',
    '   kBmmmmBk',
    '   kk    kk',
    '    kssss k',
    '     kkkk',
    '', '', '', '', ''),

  gloves: matrix(16, 16,
    '', '',
    '   kLk    kLk',
    '  kNNLk  kLNNk',
    ' kNLLNk  kNLLNk',
    ' kNNNNk  kNNNNk',
    '  kNNNk  kNNNk',
    '  kNLNk  kNLNk',
    '   kkk    kkk',
    '', '', '', '', '', '', ''),

  boots: matrix(16, 16,
    '',
    '   kLNk   kNLk',
    '   kNNk   kNNk',
    '   kNLk   kLNk',
    '   kNNk   kNNk',
    '   kNNk   kNNk',
    '   kNNLk kLNNk',
    '  kNNNNNkNNNNNk',
    '  kkkkkk kkkkkk',
    '', '', '', '', '', '', ''),

  cloak: matrix(16, 16,
    '       kyk',
    '      kpppk',
    '    kkpppppkk',
    '   kpqpppppqpk',
    '  kqpppppppppqk',
    '  kqppcppcpppqk',
    '  kqpppppppppqk',
    '   kqppppppqk',
    '    kqppppqk',
    '     kqppqk',
    '      kqqk',
    '       kk',
    '', '', '', ''),

  ring: matrix(16, 16,
    '', '',
    '       kck',
    '      kcyck',
    '     kyYYYyk',
    '    kyYk kYyk',
    '    kYk   kYk',
    '    kYk   kYk',
    '     kYk kYk',
    '      kYYYk',
    '       kkk',
    '', '', '', '', ''),
};

export const PX = { player, playerWalk, npc, monster, item };
