// pixelart.js - original late-16-bit JRPG sprites with a medieval isekai vocabulary.
// Each sprite resolves to a matrix of 1-char pixels; PAL maps chars to colors.
export const PAL = {
  ' ': null, '.': null,               // transparent
  k: '#140a12',                       // hard outline / deepest occlusion
  s: '#f4cfa2', h: '#cf9668',         // skin light / shadow
  w: '#eef5ff', m: '#9eabbc', b: '#606b7b', B: '#343c49', // steel ramp
  r: '#ef744d', R: '#9e3929', O: '#c75f35', // scarlet / oxblood / copper
  u: '#6673e8', U: '#35409b', c: '#96edff', // blue cloth / shadow / magic rim
  g: '#68c57c', G: '#2f7844',         // green wool
  y: '#f2ca59', Y: '#9b7618',         // gold light / shadow
  n: '#8b6739', N: '#51361f', o: '#bd8a4c', L: '#e0ad63', // leather ramp
  p: '#a486dc', q: '#563b91',         // violet cloth / shadow
  i: '#ded3bb', I: '#776c5c',         // undyed wool / shadow
  a: '#a7a7a5', A: '#57595e',         // stone light / shadow
  l: '#65d4f5', z: '#187ca9',         // ice / spectral cyan
  x: '#ffffff', d: '#26151c',         // white flare / dark detail
  f: '#3f7d3a', F: '#2f6a2c', j: '#57a34d', // grass tones
  v: '#2b6ca3', V: '#1d5080', C: '#66a8d8', // water tones
  t: '#b79b6b', T: '#9c8250',         // path
  e: '#6b6f78', E: '#565a62',         // dungeon floor
};

// Source rows may omit trailing transparency. The renderer still receives exact rectangles.
const matrix = (width, height, ...source) => {
  if (source.length !== height) throw new Error(`Pixel matrix expected ${height} rows, got ${source.length}`);
  return source.map((row, y) => {
    if (row.length > width) throw new Error(`Pixel matrix row ${y} exceeds ${width}px`);
    for (const ch of row) if (!(ch in PAL)) throw new Error(`Unknown pixel palette key '${ch}'`);
    return row.padEnd(width, ' ');
  });
};

// ---- player classes (16x22, facing down) ----
const player = {
  blade: matrix(16, 22,
    '',
    '      kRk',
    '     krrrk',
    '    kBwwwBk',
    '    kwmwmwk',
    '    kBmmmBk',
    '     ksssk',
    '     ksddk',
    '     kshhk',
    '   kkRrrRkk',
    '  kmkRwyRkmk',
    '  kBkRwwwRBk',
    '  kBkRwywRBk',
    '  kBkRwwwRBk',
    '   kkBmmmkk',
    '    kmyymk',
    '    kmmmmk',
    '    kN  Nk',
    '    kn  nk',
    '    kN  Nk',
    '    kk  kk',
    ''),

  berserker: matrix(16, 22,
    '',
    '    krRrk',
    '   krRRRrk',
    '   kRshsRk',
    '   ksddhsk',
    '   kshhhsk',
    '    khhhk',
    ' kAkkNNNkkAak',
    'kAAkNrrrNkAAak',
    ' kAkNyyyNkAak',
    '  kkNrrrNkk nk',
    '   kNnnnNk  nk',
    '   kNNNNNk  nk',
    '    kNNNk   nk',
    '    kNNNk   kk',
    '    ks sk',
    '    kh hk',
    '   kN   Nk',
    '   kn   nk',
    '   kN   Nk',
    '   kk   kk',
    ''),

  mage: matrix(16, 22,
    '       kyk',
    '      kuyk',
    '     kuuuyk',
    '    kuuuuuyk',
    '   kuuuUuuuuk',
    '   kushhsuuk',
    '   kusddsUuk',
    '   kushhsuuk',
    '    kuuUuuk kyk',
    '   kuuyyuuuk kyk',
    '  kuuUyUuuuukkyk',
    '  kuuuYuuUuuk nk',
    '  kuuuYuuuUuk nk',
    '   kuuYUUuuk  nk',
    '   kuuYuuuuk  nk',
    '    kuYuuuk   nk',
    '    kuuuuuk   kk',
    '     ku uuk',
    '     ku  uk',
    '    kN   Nk',
    '    kk   kk',
    ''),

  ranger: matrix(16, 22,
    '',
    '     kggk',
    '    kgGGgk',
    '   kgGggGgk',
    '   kgshhsgk',
    '   kgsddsgk',
    '   kgshhsgk',
    '    kggggk',
    ' k  kgGGgk  k',
    'knk kggggk kyk',
    'knGkkgyygkkyyk',
    'knGkggGGggk yk',
    'knk kggggk  yk',
    ' k  kgGggk  yk',
    '    kggggk  kk',
    '    kNggNk',
    '    kN  Nk',
    '    kn  nk',
    '   kN    Nk',
    '   kn    nk',
    '   kk    kk',
    ''),

  paladin: matrix(16, 22,
    '     kyYyk',
    '    kywywyk',
    '   kBwwwwwBk',
    '   kwmwmwmwk',
    '   kBwwwwwBk',
    '     ksssk',
    '     ksddk',
    '     kshhk',
    '   kkwyyywkk',
    '  kmkwxYxwmkyk',
    ' kyYkwxxxwkYyk',
    'kyYYkwwywwkYyk',
    'kyYYkwwwwwk nyk',
    ' kyYkBmmmBk nnk',
    '  kkkmwymk  nnk',
    '    kmwwmk  kkk',
    '    kBmmBk',
    '    kN  Nk',
    '    kn  nk',
    '    kY  Yk',
    '    kk  kk',
    ''),

  monk: matrix(16, 22,
    '',
    '     kNNNk',
    '    kNsssNk',
    '    kshhhsk',
    '    ksddhsk',
    '    kshhhsk',
    '     khhhk',
    '   kkiiiiikk',
    '  kskiiiiiksk',
    ' ksskIiyiIkssk',
    ' ksskkiyikkssk',
    '  kskiiiiiksk',
    '   kIiiiiIk',
    '    kiiiyk',
    '    kIiiIk',
    '    kii iik',
    '    ki   ik',
    '    kN  Nk',
    '   kN    Nk',
    '   kn    nk',
    '   kk    kk',
    ''),

  elementalist: matrix(16, 22,
    '      kcyk',
    '     kcccyk',
    '    kuuuuuk',
    '   kuUppUuuk',
    '   kushhsuuk',
    '   kusddsUuk',
    '   kushhsuuk',
    '    kuuUuuk',
    ' kc kpuYupk kr',
    'kcckpuuUupkrrk',
    ' kckpUcucUpkrRk',
    '  kkpuuUuupk kk',
    '   kpUuyUUpk',
    '   kpuuUuupk',
    '    kpuuupk',
    '    kpUUpk',
    '    kpuupk',
    '    kq  qk',
    '    kp  pk',
    '   kq    qk',
    '   kk    kk',
    ''),
};

// ---- NPCs by role (16x16) ----
const npc = {
  shop: matrix(16, 16,
    '     kLLLk',
    '   kkNNNNNkk',
    '    kNsssNk',
    '    kshhhsk',
    '    ksddhsk',
    '    kshhhsk',
    '     khhhk',
    '   kkooooikk',
    '  knkoLyoiknk',
    '  knkooooi knk',
    '  k kIiiiIk k',
    '    kiiyiik',
    '    kIiiIk',
    '    kN  Nk',
    '    kk  kk',
    ''),

  quest: matrix(16, 16,
    '       kLk',
    '    kgggkLk',
    '   kgGGGgkk',
    '   kgshhsgk',
    '   kgsddsgk',
    '   kgshhsgk',
    '    kggggk',
    '  kkgiiyiikk',
    ' knkgiiyiikyk',
    ' knkggGGggkyk',
    '  kkggggggkkk',
    '    kggggk',
    '    kGggGk',
    '    kN  Nk',
    '    kk  kk',
    ''),

  guild: matrix(16, 16,
    '     krRrk',
    '    kBwwwBk',
    '    kwmwmwk',
    '    kBmmmBk',
    '     ksssk',
    '     ksddk',
    '   kkmwywmkk',
    '  kmkmwwwmkmk',
    '  kBkmyyymkBk',
    '  kBkmyRymkBk',
    '   kkBmmmBkk',
    '    kmwwmk',
    '    kBmmBk',
    '    kN  Nk',
    '    kk  kk',
    ''),

  story: matrix(16, 16,
    '     kpppk',
    '    kpqqqpk',
    '    kixxxik',
    '    kishsik',
    '    kisdsik',
    '    kishsik',
    '     kiiik',
    '   kkpyyypkk',
    '  kikpqyqpkik',
    '  kikpppppkik',
    '   kqpiiipqk',
    '    kpiiipk',
    '    kqiiiqk',
    '    kp  pk',
    '    kk  kk',
    ''),
};

// ---- monsters (16x16, bosses 24x24) ----
const monster = {
  slime: matrix(16, 16,
    '', '',
    '       kk',
    '    kkkllkk',
    '   kllcllllk',
    '  kclllllllzk',
    ' klllxxlllllzk',
    ' klllddlllldzk',
    'kllllllllllllzk',
    'kllzlllllzlllzk',
    'klllllllllllllk',
    ' kzlllllllllzk',
    '  kzzlllllzzk',
    '   kzzzzzzzk',
    '     kkkkk',
    ''),

  goblin: matrix(16, 16,
    '     krrrk',
    '   krrRRRrk',
    '  krRkkkkRrk',
    '  kk kgggk',
    ' kgggggggggk',
    'kGgggGgggGggk',
    'kgydgggggdgygk',
    'kgggNgggNggggk',
    ' kgggggggggk',
    ' kkGNNNNNGkk',
    'knkGoooooGkkyk',
    'knkGGGGGGGk kyk',
    ' kk kG Gk  kyk',
    '    kg gk  kk',
    '    kk kk',
    ''),

  wolf: matrix(16, 16,
    '',
    ' kk         kk',
    'kAk        kAAk',
    'kAAkk    kkAAAk',
    'kAaAAkkkkAAAAAk',
    ' kAayAAAAAAAaAk',
    ' kAdAAAAAAAAdAk',
    'kAAAAAAAAAAAaAk',
    'kAaAAAAAAAAAAAk',
    ' kkAAAAAAAaAk',
    '  kAk kk kAAk',
    '  kAk kk kAak',
    '  kk  kk  kk',
    '', '', ''),

  thornback_boar: matrix(16, 16,
    '',
    '   kGk     kGk',
    '  kGGk   kkGGk',
    ' kkNNkkkkNNGGk',
    'kNnnNNNNNnNNNk',
    'kNnoooooooNNNk',
    ' kNodoodooNNk',
    ' kNnoooooNNNk',
    '  kNNNNNNNNk',
    '  kkN NN Nkk',
    ' knkN NN Nknk',
    ' kk k kk k kk',
    '', '', '', ''),

  shade: matrix(16, 16,
    '',
    '     kkkkk',
    '    kqqqqqk',
    '   kqpppppqk',
    '   kpcppcpqk',
    '   kpdddpqk',
    '  kqppppppqk',
    ' kqppqppqppqk',
    ' kppppppppppk',
    '  kqppppppqk',
    '   kqppppqk',
    '   kqpkppqk',
    '   kk k  kk',
    '     k k',
    '', ''),

  mire_leech: matrix(16, 16,
    '', '',
    '     kGGk',
    '   kkGggGkk',
    '  kGggggggGk',
    ' kGgNggggNggk',
    'kGgggddddgggGk',
    'kggggggggggggk',
    ' kGggGkkGggGk',
    '  kGGk  kGGk',
    '   kk    kk',
    '', '', '', '', ''),

  drowned_acolyte: matrix(16, 16,
    '     kVVVk',
    '    kVvCvVk',
    '    kCwwwCk',
    '    kwdwdwk',
    '    kBmmmBk',
    '   kkVvVvVkk',
    '  kVkVlllVkVk',
    '  kVkVvCvVkVk',
    '   kkVvVvVkk',
    '    kVvVvVk',
    '    kCVVCk',
    '    kV  Vk',
    '    kv  vk',
    '    kk  kk',
    '', ''),

  ruin_golem: matrix(24, 24,
    '', '',
    '        kkAAkk',
    '       kAaaaaAk',
    '       kaYYYYak',
    '       kaYrrYak',
    '       kAaaaaAk',
    '    kkkkAAaaAAkkkk',
    '  kkAAkkAaaaaAkkAAkk',
    ' kAaaAkkaawwaakkAaaAk',
    ' kAaAAkkaammaakAAaAAk',
    ' kAaaaAkAayYyaAkAaaaAk',
    '  kAAAkkaaaaaakkAAAk',
    '   kkk kAaaAaAk kkk',
    '       kAaAaAk',
    '       kAaaaAk',
    '       kaAAaak',
    '      kkAaaAkk',
    '     kAAk  kAAk',
    '     kAak  kAak',
    '     kAAk  kAAk',
    '     kkkk  kkkk',
    '', ''),

  frost_wolf: matrix(16, 16,
    '',
    ' kk         kk',
    'kzk        kzzk',
    'kzzkk    kkzzzk',
    'kzlzzkkkkzzzzzk',
    ' kzzxllllllllzk',
    ' kzdlcllllcldzk',
    'kzlllllllllllzk',
    'kzlcllllllllzzk',
    ' kkzzllllllzzk',
    '  kzk kk kzzk',
    '  kzk kk kzzk',
    '  kk  kk  kk',
    '', '', ''),

  ice_wraith: matrix(16, 16,
    '',
    '      kkk',
    '    kklclkk',
    '   klllllllzk',
    '  kllxlllxllzk',
    '  klldllldllzk',
    ' klllllllllllzk',
    'kllzkllllkzllzk',
    ' klllllllllllzk',
    '  kzlllllllzzk',
    '   kzlcllzzk',
    '   klkllklk',
    '   kk kk kk',
    '      k',
    '', ''),

  rime_harpy: matrix(16, 16,
    '      kck',
    '     kclck',
    ' kk  klllk  kk',
    'kzzkklddlkkzzk',
    ' kzlllllllzzk',
    '  kzlclcllzk',
    '   kllllllk',
    '  kkzllllzkk',
    ' kzk kllk kzk',
    'kk   kllk   kk',
    '     kzlk',
    '     kllk',
    '    kzk kzk',
    '    kk   kk',
    '', ''),

  sand_stalker: matrix(16, 16,
    '',
    '  kk       kk',
    ' kLNk     kNLk',
    ' kLoNkkkkkNoLk',
    '  kLoooooooLk',
    ' kLoLoooooLoLk',
    'koodooooooodook',
    'koooNNNNNoooook',
    ' kLooLyoLooLk',
    '  kNNNNNNNNk',
    '  knoNNNNonk',
    ' kk kN Nkk kk',
    'knk ko ok knk',
    'kk  kk kk  kk',
    '', ''),

  ember_imp: matrix(16, 16,
    '  kr         rk',
    '  kRrk     krRk',
    '   krkkkkkrrk',
    '   kRrrrrrRk',
    '  krOrrrrrOrk',
    '  krrdrrrdrrk',
    '  krrryyrrrrk',
    ' kRrrrrrrrrRk',
    'krRkRRRRRRkRrk',
    ' kk kRrrRk kk',
    '    kRyyRk',
    '    kRrrRk',
    '    kr  rk',
    '    kk  kk',
    '', ''),

  magma_beetle: matrix(16, 16,
    '',
    '   kk    kk',
    '  kRrkkkkRrk',
    ' kRROrrrrORRk',
    'kRRRROOORRRRk',
    'kROrryyyyrrORk',
    'kRRrrddddrrRRk',
    ' kRROrrrrORRk',
    '  kRRROORRRk',
    ' kk kRrrRk kk',
    'kRk kRrrRk kRk',
    'kk  kk  kk  kk',
    '', '', '', ''),

  flame_dragon: matrix(24, 24,
    '',
    '           kRk',
    '      kk  krRrk  kk',
    '    krrRkkrRRRrkkRrrk',
    '   krRRRRRRROORRRRRRrk',
    '  krRyyRRRrrrrRRRyyRRrk',
    '  kRyyyRRrdrrdRRRyyyRRk',
    '   kRRRRRrrrrrrRRRRRRk',
    '    kkrRRROOORRRRrkk',
    '      krRRRRRRRrk',
    '   kkkrROyyyyORrkkk',
    '  kRrkkRrrrrrrRkkRrk',
    ' krRk kRRROORRRk kRrk',
    ' kRk  krRRRRRRrk  kRk',
    ' kk   kRRROORRRk   kk',
    '      krRRRRRRrk',
    '      kRROOORRk',
    '     kRRRk kRRRk',
    '    krRrk   krRrk',
    '    kRrk     kRrk',
    '    kkk       kkk',
    '', '', ''),

  void_wisp: matrix(16, 16,
    '',
    '       kk',
    '     kkppkk',
    '    kppqqppk',
    '   kppcxxcppk',
    '  kqppcxxcppqk',
    '  kppppccppppk',
    '   kqppppppqk',
    '    kqppppqk',
    '     kkppkk',
    '   kk  kk  kk',
    '  kppk kq kppk',
    '   kk     kk',
    '', '', ''),

  star_reaver: matrix(16, 16,
    '      kppk',
    '     kpqppk',
    '    kBwwwBkk',
    '    kwdwdwk yk',
    '    kBmmmBk wyk',
    '   kkqpppqkkwk',
    '  kBkqpypqkBwk',
    '  kmkqpppqkmwk',
    '  kBkqpppqkByk',
    '   kkqpppqkk k',
    '    kqpppqk',
    '    kBppBk',
    '    kq  qk',
    '    kp  pk',
    '    kk  kk',
    ''),

  astral_knight: matrix(16, 16,
    '     kpppk',
    '    kBwwwBk',
    '    kwcwcwk',
    '    kBmmmBk',
    '   kkwwwwwkk',
    '  kmkwcpcwkmk',
    '  kBkwwpwwkBk',
    '  kBkwwpwwkBk',
    '   kkwwpwwkk',
    '    kBmmmBk',
    '    kmwwwmk',
    '    kBmmBk',
    '    kq  qk',
    '    kp  pk',
    '    kk  kk',
    ''),

  rift_manta: matrix(16, 16,
    '', '',
    '       kk',
    '    kkkppkkk',
    '  kkqppccppqkk',
    ' kqpppcxxcpppqk',
    'kqppppcddcppppqk',
    ' kpqqppccppqqpk',
    '  kkqppppppqkk',
    '    kqppppqk',
    '     kpqqpk',
    '     kq  qk',
    '      k  k',
    '', '', ''),

  elderwood_treant: matrix(24, 24,
    '',
    '        kkGGGkk',
    '      kkGggggGkk',
    '    kkGgGGggGGgGkk',
    '   kGggGGGGGGGGggGk',
    '  kGgGGgGGGGgGGGgGk',
    '   kGGGkkNNNNkkGGGk',
    '    kkk kNnnNk kkk',
    '  kk    kNxNk    kk',
    ' kNNkk  kNNNk  kkNNk',
    'kNnnNkkkNnNnNkkkNnnNk',
    'kNNNNNNNNNNNNNNNNNNNk',
    ' kkNNnNNNNNNNNnNNNkk',
    '   kkNNNNNNNNNNkk',
    '     kNnNNNNnNk',
    '     kNNNNNNNNk',
    '     kNNNkkNNNk',
    '    kNnNk  kNnNk',
    '   kNNNk    kNNNk',
    '   kNnNk    kNnNk',
    '   kkkk      kkkk',
    '', '', ''),

  frost_revenant: matrix(24, 24,
    '',
    '        kc c ck',
    '       kclclclck',
    '       klllllllk',
    '      klzzlzzllk',
    '     kllxlllxlllk',
    '     klldllldlllzk',
    '      kllllllllk',
    '    kkkzlllllzkkk',
    '   kzlllllllllllzk',
    '  kllzklllllllzkllk',
    '  klzk klllllk kzlk',
    '  kck  kzlllzk  kck',
    '   k   klllllk   k',
    '       kzlllzk',
    '       klllllk',
    '      kzlllllzk',
    '      kllk kllk',
    '      klk   klk',
    '      kk     kk',
    '', '', '', ''),

  nullking: matrix(24, 24,
    '',
    '        kyYyYyk',
    '       kyYYYYYyk',
    '        kqqqqqk',
    '       kqpppppqk',
    '      kqpcxxcppqk',
    '      kqpdddddpqk',
    '      kqpppppppqk',
    '    kkqppqppqppqkk',
    '   kppkqpppppqkppk',
    '  kqppkkqpppqkkppqk',
    '  kppk kqpppqk kppk',
    '  kqk  kqqpqqk  kqk',
    '   k   kqpppqk   k',
    '       kqpppqk',
    '       kqpqpqk',
    '       kqpppqk',
    '       kqk kqk',
    '       kpk kpk',
    '       kk   kk',
    '', '', '', ''),
};

// ---- player WALK frames: cloth, weapon and stance all shift with the step ----
const walkFrame = (base, replacements) => matrix(
  base[0].length,
  base.length,
  ...base.map((row, index) => replacements[index] ?? row),
);
const playerWalk = {
  blade: walkFrame(player.blade, {
    10: ' kmkRwyRkmk', 11: ' kBkRwwwRBk', 14: '  kkBmmmkk', 15: '   kmyymk',
    16: '   kmmmmk', 17: '   kN   Nk', 18: '  kn     nk', 19: '  kN     Nk', 20: '  kk     kk',
  }),
  berserker: walkFrame(player.berserker, {
    8: ' kAAkNrrrNkAAak', 9: 'kAAkNyyyNkAak', 13: '   kNNNk   nk', 14: '   kNNNk   kk',
    15: '   ks  sk', 16: '   kh  hk', 17: '  kN    Nk', 18: ' kn      nk', 19: ' kN      Nk', 20: ' kk      kk',
  }),
  mage: walkFrame(player.mage, {
    10: ' kuuUyUuuuukkyk', 11: ' kuuuYuuUuuk nk', 14: '  kuuYuuuuk  nk', 15: '   kuYuuuk   nk',
    16: '   kuuuuuk   kk', 17: '    ku  uuk', 18: '    ku   uk', 19: '   kN    Nk', 20: '   kk    kk',
  }),
  ranger: walkFrame(player.ranger, {
    9: 'knk kggggkkyk', 10: 'knGkkgyygk yyk', 12: 'knk kggggk yk', 14: '   kggggk  kk',
    15: '   kNggNk', 16: '   kN   Nk', 17: '  kn     nk', 18: '  kN     Nk', 19: '  kn     nk', 20: '  kk     kk',
  }),
  paladin: walkFrame(player.paladin, {
    10: 'kyYkwxxxwkYyk', 11: 'kyYYkwwywwkYyk', 13: 'kyYkBmmmBk nnk', 14: ' kkkmwymk  nnk',
    15: '   kmwwmk  kkk', 16: '   kBmmBk', 17: '   kN   Nk', 18: '  kn     nk', 19: '  kY     Yk', 20: '  kk     kk',
  }),
  monk: walkFrame(player.monk, {
    8: ' kskiiiiiksk', 9: 'ksskIiyiIkssk', 11: ' kskiiiiiksk', 13: '   kiiiyk',
    14: '   kIiiIk', 15: '   kii  iik', 16: '   ki    ik', 17: '   kN   Nk', 18: '  kN     Nk', 19: '  kn     nk', 20: '  kk     kk',
  }),
  elementalist: walkFrame(player.elementalist, {
    8: 'kcc kpuYupk kr', 9: ' kckpuuUupkrrk', 10: '  kpUcucUpkrRk', 13: '  kpuuUuupk',
    14: '   kpuuupk', 15: '   kpUUpk', 16: '   kpuupk', 17: '   kq   qk', 18: '  kp     pk', 19: '  kq     qk', 20: '  kk     kk',
  }),
};

// ---- 16x16 item / equipment icons ----
const item = {
  sword: matrix(16, 16,
    '       kwk',
    '      kwxk',
    '      kwmk',
    '      kwmk',
    '      kwmk',
    '      kwmk',
    '     kwwmk',
    '    kBwwwmk',
    '   kykkYkkyk',
    '      kLk',
    '      kNk',
    '      kLk',
    '      kkk',
    '', '', ''),

  dagger: matrix(16, 16,
    '       kk',
    '      kwk',
    '      kwk',
    '     kwmk',
    '     kwmk',
    '    kBwmk',
    '   kykkYk',
    '      kLk',
    '      kNk',
    '      kk',
    '', '', '', '', '', ''),

  greatsword: matrix(16, 16,
    '      kwwk',
    '     kwxwmk',
    '     kwywmk',
    '     kwywmk',
    '     kwywmk',
    '     kwywmk',
    '     kwywmk',
    '    kBwyywmk',
    '  kyYkkwYwkkYyk',
    '      kLLk',
    '      kNNk',
    '      kLLk',
    '       kk',
    '', '', ''),

  tunic: matrix(16, 16,
    '', '',
    '   kk     kk',
    '  kiikiiiikik',
    ' kiiikiiiikiiik',
    ' kIiiiiiiiiiIik',
    '  kIiiiiiiiIk',
    '   kiiiyiiik',
    '   kiiiiiiiik',
    '   kIiiiiiIik',
    '    kkkkkkk',
    '', '', '', '', ''),

  vest: matrix(16, 16,
    '', '',
    '   kk     kk',
    '  kNLkNNNkLNk',
    ' kNLLkNNNkLLNk',
    ' kNNNkNyNkNNNk',
    '  kNNkNyNkNNk',
    '   kNkNyNkNk',
    '   kNkNNNkNk',
    '   kNNNNNNNk',
    '    kkkkkkk',
    '', '', '', '', ''),

  plate: matrix(16, 16,
    '',
    '     kwwwk',
    '   kkBmmmBkk',
    '  kmkwmwmkmk',
    ' kBmkwwwwwkmBk',
    ' kBmkwwywwkmBk',
    '  kmkwwwwwkmk',
    '   kBmwymBk',
    '   kmwwwwmk',
    '   kBmmmmBk',
    '    kkkkkk',
    '', '', '', '', ''),

  potred: matrix(16, 16,
    '',
    '      kkk',
    '     kwmwk',
    '      kkk',
    '     kwwwk',
    '    kwxwwmk',
    '   kwrrrrwmk',
    '   kwrOrrwmk',
    '   kwrRRrwmk',
    '   kwrrrrwmk',
    '    kmwwmk',
    '     kkkk',
    '', '', '', ''),

  potblue: matrix(16, 16,
    '',
    '      kkk',
    '     kwmwk',
    '      kkk',
    '     kwwwk',
    '    kwxwwmk',
    '   kwuuuuwmk',
    '   kwucUuwmk',
    '   kwuUUuwmk',
    '   kwuuuuwmk',
    '    kmwwmk',
    '     kkkk',
    '', '', '', ''),

  gem: matrix(16, 16,
    '', '',
    '       kk',
    '      kcck',
    '     kcllzk',
    '    kcllllzk',
    '   kclxllllzk',
    '    klllllzk',
    '     klllzk',
    '      klzk',
    '       kk',
    '', '', '', '', ''),

  scroll: matrix(16, 16,
    '', '',
    '   kkkkkkkkk',
    '  kiiiiiiiiik',
    '  kixkykkyiik',
    '  kikyYyYkiik',
    '  kikyRyYkiik',
    '  kixkykkyiik',
    '  kIiiiiiiiIk',
    '   kkkkkkkkk',
    '', '', '', '', '', ''),

  core: matrix(16, 16,
    '',
    '       kk',
    '     kkyykk',
    '    kyROORyk',
    '   kyRrrrrRyk',
    '   kRrrccrrRk',
    '   kRrcxxcrRk',
    '   kRrrccrrRk',
    '    kyROORyk',
    '     kkyykk',
    '       kk',
    '', '', '', '', ''),

  helm: matrix(16, 16,
    '', '',
    '     kwwwk',
    '   kkBmmmBkk',
    '  kBwwwwwwwBk',
    '  kwmwmwmwmwk',
    '  kBwwywywwBk',
    '   kBmmmmBk',
    '   kk    kk',
    '    kssss k',
    '     kkkk',
    '', '', '', '', ''),

  gloves: matrix(16, 16,
    '', '',
    '   kLk    kLk',
    '  kNNLk  kLNNk',
    ' kNLLNk  kNLLNk',
    ' kNNNNk  kNNNNk',
    '  kNNNk  kNNNk',
    '  kNLNk  kNLNk',
    '   kkk    kkk',
    '', '', '', '', '', '', ''),

  boots: matrix(16, 16,
    '',
    '   kLNk   kNLk',
    '   kNNk   kNNk',
    '   kNLk   kLNk',
    '   kNNk   kNNk',
    '   kNNk   kNNk',
    '   kNNLk kLNNk',
    '  kNNNNNkNNNNNk',
    '  kkkkkk kkkkkk',
    '', '', '', '', '', '', ''),

  cloak: matrix(16, 16,
    '       kyk',
    '      kpppk',
    '    kkpppppkk',
    '   kpqpppppqpk',
    '  kqpppppppppqk',
    '  kqppcppcpppqk',
    '  kqpppppppppqk',
    '   kqppppppqk',
    '    kqppppqk',
    '     kqppqk',
    '      kqqk',
    '       kk',
    '', '', '', ''),

  ring: matrix(16, 16,
    '', '',
    '       kck',
    '      kcyck',
    '     kyYYYyk',
    '    kyYk kYyk',
    '    kYk   kYk',
    '    kYk   kYk',
    '     kYk kYk',
    '      kYYYk',
    '       kkk',
    '', '', '', '', ''),
};

export const PX = { player, playerWalk, npc, monster, item };
